# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicObjs(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def Count(self):
        return self.obj.Count

    @property
    def _NewEnum(self):
        return self.obj._NewEnum

    @property
    def ItemType(self):
        return self.obj.ItemType

    @property
    def Next(self):
        return self.obj.Next

    @property
    def Add(self):
        return self.obj.Add

    @property
    def Merge(self):
        return self.obj.Merge

    @property
    def Remove(self):
        return self.obj.Remove

    @property
    def Reset(self):
        return self.obj.Reset

    @property
    def Select(self):
        return self.obj.Select

    @property
    def Sort(self):
        return self.obj.Sort

    @property
    def Item(self):
        return self.obj.Item

