# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicGate(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Name(self):
        return self.obj.Name

    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def Component(self):
        return self.obj.Component

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def selected(self):
        return self.obj.selected

    @Name.setter
    def Name(self, Name):
        self.obj.Name=Name

    @property
    def Sheet(self):
        return self.obj.Sheet

    @property
    def SwapClass(self):
        return self.obj.SwapClass

    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def IsConnector(self):
        return self.obj.IsConnector

    @property
    def ReflectedX(self):
        return self.obj.ReflectedX

    @selected.setter
    def selected(self, selected):
        self.obj.selected=selected

    @property
    def ReflectedY(self):
        return self.obj.ReflectedY

    @ReflectedX.setter
    def ReflectedX(self, ReflectedX):
        self.obj.ReflectedX=ReflectedX

    @property
    def Rotated90(self):
        return self.obj.Rotated90

    @ReflectedY.setter
    def ReflectedY(self, ReflectedY):
        self.obj.ReflectedY=ReflectedY

    @property
    def Visibility(self):
        return self.obj.Visibility

    @Rotated90.setter
    def Rotated90(self, Rotated90):
        self.obj.Rotated90=Rotated90

    @property
    def Number(self):
        return self.obj.Number

    @property
    def Move(self):
        return self.obj.Move

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def PartType(self):
        return self.obj.PartType

    @Visibility.setter
    def Visibility(self, Visibility):
        self.obj.Visibility=Visibility

    @PartType.setter
    def PartType(self, PartType):
        self.obj.PartType=PartType

