# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicApp(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def FullName(self):
        return self.obj.FullName

    @property
    def Visible(self):
        return self.obj.Visible

    @property
    def Name(self):
        return self.obj.Name

    @property
    def ActiveDocument(self):
        return self.obj.ActiveDocument

    @property
    def DefaultFilePath(self):
        return self.obj.DefaultFilePath

    @Visible.setter
    def Visible(self, Visible):
        self.obj.Visible=Visible

    @property
    def Preference(self):
        return self.obj.Preference

    @DefaultFilePath.setter
    def DefaultFilePath(self, DefaultFilePath):
        self.obj.DefaultFilePath=DefaultFilePath

    @property
    def StatusBarText(self):
        return self.obj.StatusBarText

    @Preference.setter
    def Preference(self, Preference):
        self.obj.Preference=Preference

    @property
    def ProgressBar(self):
        return self.obj.ProgressBar

    @StatusBarText.setter
    def StatusBarText(self, StatusBarText):
        self.obj.StatusBarText=StatusBarText

    @property
    def Version(self):
        return self.obj.Version

    @property
    def Quit(self):
        return self.obj.Quit

    @property
    def OpenDocument(self):
        return self.obj.OpenDocument

    @property
    def RunMacro(self):
        return self.obj.RunMacro

    @property
    def ProcessCommand(self):
        return self.obj.ProcessCommand

    @property
    def ProcessParameter(self):
        return self.obj.ProcessParameter

    @property
    def ProcessPointer(self):
        return self.obj.ProcessPointer

    @property
    def StrNumCmp(self):
        return self.obj.StrNumCmp

    @property
    def LockServer(self):
        return self.obj.LockServer

    @property
    def UnlockServer(self):
        return self.obj.UnlockServer

    @property
    def Measure(self):
        return self.obj.Measure

    @property
    def DisplayLibraryPart(self):
        return self.obj.DisplayLibraryPart

    @property
    def ListLibraryParts(self):
        return self.obj.ListLibraryParts

    @property
    def DisplayLibraryPcbDecal(self):
        return self.obj.DisplayLibraryPcbDecal

    @property
    def IsServerBusy(self):
        return self.obj.IsServerBusy

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Libraries(self):
        return self.obj.Libraries

    @property
    def GetLibraryItems(self):
        return self.obj.GetLibraryItems

    @ProgressBar.setter
    def ProgressBar(self, ProgressBar):
        self.obj.ProgressBar=ProgressBar

