# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os

__author__ = 'SayCV'



# PlogObjectType
# PADS Logic Database Object Type Constants


plogObjectTypeUnknown = 0

plogObjectTypeComponent = 1

plogObjectTypeNet = 2

plogObjectTypePin = 3

plogObjectTypeGate = 4

plogObjectTypePartType = 8

plogObjectTypeLibrary = 18

plogObjectTypeLibraryItem = 19

plogObjectTypeApplication = 20

plogObjectTypeAll = 9999




# PlogUnit
# PADS Logic Unit Constants


plogUnitCurrent = 0

plogUnitDatabase = 1

plogUnitMils = 2

plogUnitInch = 3

plogUnitMetric = 4

plogUnitDrawArea = 99




# PlogGridType
# PADS Logic Grid Type Constants


plogGridNone = 0

plogGridDesign = 1

plogGridDisplay = 3

plogGridAll = 9999




# PlogASCIIVersion
# PADS Logic output ASCII Version Constants


plogASCIIVerCurrent = 0

plogASCIIVer2007 = 1

plogASCIIVer2005_2 = 2

plogASCIIVer2005 = 3




# PlogNetListVersion
# PADS Logic NetList Version Constants


plogPowerPCBNetListVerCurrent = 0

plogPowerPCBNetListVerPrevious = 1

plogPowerPCBNetListVer2005_2 = 2

plogPowerPCBNetListVer2005 = 3




# PlogPinElectricalType
# PADS Logic Pin Electrical Type Constants


plogElectricalTypeUnknown = 0

plogElectricalTypeSource = 1

plogElectricalTypeBidirectional = 2

plogElectricalTypeOpenCollector = 3

plogElectricalTypeOrTieableSource = 4

plogElectricalTypeTristate = 5

plogElectricalTypeLoad = 6

plogElectricalTypeTerminator = 7

plogElectricalTypePower = 8

plogElectricalTypeGround = 9




# PlogGateVisibility
# PADS Logic Gate Visibility Constants


plogAttrVisibility = 0

plogAttrNameVisibility = 1

plogRefDesVisibility = 2

plogPartTypeVisibility = 3

plogPinNumberVisibility = 4

plogPinNameVisibility = 5

plogPCBDecalVisibility = 6

plogPCBDecalNameVisibility = 7




# PlogDefaultPosition
# PADS Logic Default Position Constants


plogDefaultPositionX = 0x80000000

plogDefaultPositionY = 0x80000000




# PlogMeasureFormat
# PADS Logic Measure Format Constants


plogMeasureFormatStandard = 0

plogMeasureFormatCurrent = 1

plogMeasureFormatShort = 2

plogMeasureFormatLong = 3




# PlogLibraryItemType
# PADS Logic Library Item Type Constants


plogLibraryItemTypePartType = 0

plogLibraryItemTypeDecal = 1

plogLibraryItemTypeLogicDrawing = 2

plogLibraryItemTypeDrawing = 3

plogLibraryItemTypeAll = 9999




# PlogImportLibMode
# PADS Logic Library Import Type Constants


plogImportLibModeSilentOverwrite = 1

plogImportLibModeNoLocalOverwrite = 2

plogImportLibModeNoGlobalOverwrite = 3

plogImportLibModePromptLocalOverwrite = 4

plogImportLibModePromptGlobalOverwrite = 5




# PlogDocumentColor
# PADS Logic Document Color


plogDocumentColorBackground = 0

plogDocumentColorSelection = 1

plogDocumentColorConnection = 2

plogDocumentColorBus = 3

plogDocumentColorLine = 4

plogDocumentColorPart = 5

plogDocumentColorHierarchicalComp = 6

plogDocumentColorText = 7

plogDocumentColorTextBox = 8

plogDocumentColorRefDes = 9

plogDocumentColorRefDesBox = 10

plogDocumentColorPartType = 11

plogDocumentColorPartTypeBox = 12

plogDocumentColorPartText = 13

plogDocumentColorPartTextBox = 14

plogDocumentColorPinNumber = 15

plogDocumentColorPinNumberBox = 16

plogDocumentColorNetName = 17

plogDocumentColorNetNameBox = 18

plogDocumentColorField = 19

plogDocumentColorFieldBox = 20



