# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBAttr(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def value(self):
        return self.obj.value

    @property
    def Name(self):
        return self.obj.Name

    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def Measure(self):
        return self.obj.Measure

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @value.setter
    def value(self, value):
        self.obj.value=value

