# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBPad(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def PadStackLayer(self):
        return self.obj.PadStackLayer

    @property
    def Shape(self):
        return self.obj.Shape

    @property
    def Diameter(self):
        return self.obj.Diameter

    @property
    def InnerDiameter(self):
        return self.obj.InnerDiameter

    @property
    def width(self):
        return self.obj.width

    @property
    def Length(self):
        return self.obj.Length

    @property
    def Orientation(self):
        return self.obj.Orientation

    @property
    def offset(self):
        return self.obj.offset

    @property
    def CornerType(self):
        return self.obj.CornerType

    @property
    def CornerRadius(self):
        return self.obj.CornerRadius

    @property
    def Name(self):
        return self.obj.Name

