# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBText(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Name(self):
        return self.obj.Name

    @property
    def Drawing(self):
        return self.obj.Drawing

    @property
    def selected(self):
        return self.obj.selected

    @property
    def Application(self):
        return self.obj.Application

    @property
    def Text(self):
        return self.obj.Text

    @selected.setter
    def selected(self, selected):
        self.obj.selected=selected

    @property
    def Delete(self):
        return self.obj.Delete

    @Text.setter
    def Text(self, Text):
        self.obj.Text=Text

