# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBVia(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def Name(self):
        return self.obj.Name

    @property
    def selected(self):
        return self.obj.selected

    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def Net(self):
        return self.obj.Net

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @selected.setter
    def selected(self, selected):
        self.obj.selected=selected

    @property
    def TestPoint(self):
        return self.obj.TestPoint

    @property
    def DrillSize(self):
        return self.obj.DrillSize

    @property
    def Plated(self):
        return self.obj.Plated

    @TestPoint.setter
    def TestPoint(self, TestPoint):
        self.obj.TestPoint=TestPoint

    @property
    def Glued(self):
        return self.obj.Glued

    @property
    def StartLayer(self):
        return self.obj.StartLayer

    @property
    def EndLayer(self):
        return self.obj.EndLayer

    @property
    def PlaneThermal(self):
        return self.obj.PlaneThermal

    @property
    def type(self):
        return self.obj.type

    @property
    def Attributes(self):
        return self.obj.Attributes

    @Glued.setter
    def Glued(self, Glued):
        self.obj.Glued=Glued

    @property
    def Stitching(self):
        return self.obj.Stitching

    @Stitching.setter
    def Stitching(self, Stitching):
        self.obj.Stitching=Stitching

    @property
    def Highlighted(self):
        return self.obj.Highlighted

    @property
    def PadStackLayers(self):
        return self.obj.PadStackLayers

    @Highlighted.setter
    def Highlighted(self, Highlighted):
        self.obj.Highlighted=Highlighted

