# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBLayer(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Name(self):
        return self.obj.Name

    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Number(self):
        return self.obj.Number

    @Name.setter
    def Name(self, Name):
        self.obj.Name=Name

    @property
    def type(self):
        return self.obj.type

    @type.setter
    def type(self, type):
        self.obj.type=type

    @property
    def PlaneType(self):
        return self.obj.PlaneType

    @PlaneType.setter
    def PlaneType(self, PlaneType):
        self.obj.PlaneType=PlaneType

    @property
    def RoutingDirection(self):
        return self.obj.RoutingDirection

    @RoutingDirection.setter
    def RoutingDirection(self, RoutingDirection):
        self.obj.RoutingDirection=RoutingDirection

    @property
    def Visible(self):
        return self.obj.Visible

    @Visible.setter
    def Visible(self, Visible):
        self.obj.Visible=Visible

    @property
    def Enabled(self):
        return self.obj.Enabled

    @Enabled.setter
    def Enabled(self, Enabled):
        self.obj.Enabled=Enabled

    @property
    def CopperThickness(self):
        return self.obj.CopperThickness

    @property
    def SetDielectricType(self):
        return self.obj.SetDielectricType

    @property
    def GetDielectricType(self):
        return self.obj.GetDielectricType

    @property
    def SetDielectricThickness(self):
        return self.obj.SetDielectricThickness

    @property
    def GetDielectricThickness(self):
        return self.obj.GetDielectricThickness

    @property
    def SetDielectricConstant(self):
        return self.obj.SetDielectricConstant

    @property
    def GetDielectricConstant(self):
        return self.obj.GetDielectricConstant

    @property
    def SetColor(self):
        return self.obj.SetColor

    @property
    def GetColor(self):
        return self.obj.GetColor

    @CopperThickness.setter
    def CopperThickness(self, CopperThickness):
        self.obj.CopperThickness=CopperThickness

