# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBWirebond(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def Component(self):
        return self.obj.Component

    @property
    def StartPad(self):
        return self.obj.StartPad

    @property
    def EndPad(self):
        return self.obj.EndPad

    @property
    def StartX(self):
        return self.obj.StartX

    @property
    def StartY(self):
        return self.obj.StartY

    @property
    def EndX(self):
        return self.obj.EndX

    @property
    def EndY(self):
        return self.obj.EndY

    @property
    def StartOffsetX(self):
        return self.obj.StartOffsetX

    @property
    def StartOffsetY(self):
        return self.obj.StartOffsetY

    @property
    def EndOffsetX(self):
        return self.obj.EndOffsetX

    @property
    def EndOffsetY(self):
        return self.obj.EndOffsetY

    @property
    def angle(self):
        return self.obj.angle

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Name(self):
        return self.obj.Name

