# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBView(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def TopLeftX(self):
        return self.obj.TopLeftX

    @property
    def Name(self):
        return self.obj.Name

    @property
    def TopLeftY(self):
        return self.obj.TopLeftY

    @TopLeftX.setter
    def TopLeftX(self, TopLeftX):
        self.obj.TopLeftX=TopLeftX

    @property
    def BottomRightX(self):
        return self.obj.BottomRightX

    @TopLeftY.setter
    def TopLeftY(self, TopLeftY):
        self.obj.TopLeftY=TopLeftY

    @property
    def BottomRightY(self):
        return self.obj.BottomRightY

    @BottomRightX.setter
    def BottomRightX(self, BottomRightX):
        self.obj.BottomRightX=BottomRightX

    @property
    def CenterX(self):
        return self.obj.CenterX

    @property
    def CenterY(self):
        return self.obj.CenterY

    @property
    def Zoom(self):
        return self.obj.Zoom

    @property
    def PointerX(self):
        return self.obj.PointerX

    @property
    def PointerY(self):
        return self.obj.PointerY

    @property
    def Refresh(self):
        return self.obj.Refresh

    @property
    def Pan(self):
        return self.obj.Pan

    @property
    def SetExtentsToAll(self):
        return self.obj.SetExtentsToAll

    @property
    def SetExtentsToBoard(self):
        return self.obj.SetExtentsToBoard

    @property
    def SetExtents(self):
        return self.obj.SetExtents

    @property
    def SetScale(self):
        return self.obj.SetScale

    @property
    def SetExtentsToSelection(self):
        return self.obj.SetExtentsToSelection

    @BottomRightY.setter
    def BottomRightY(self, BottomRightY):
        self.obj.BottomRightY=BottomRightY

