# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBMeasure(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def value(self):
        return self.obj.value

    @value.setter
    def value(self, value):
        self.obj.value=value

    @property
    def Text(self):
        return self.obj.Text

    @property
    def Name(self):
        return self.obj.Name

    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def unit(self):
        return self.obj.unit

    @property
    def Prefix(self):
        return self.obj.Prefix

    @property
    def Number(self):
        return self.obj.Number

    @property
    def Normalize(self):
        return self.obj.Normalize

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @Text.setter
    def Text(self, Text):
        self.obj.Text=Text

