# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBPadStackLayer(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Pin(self):
        return self.obj.Pin

    @property
    def Via(self):
        return self.obj.Via

    @property
    def Number(self):
        return self.obj.Number

    @property
    def Pad(self):
        return self.obj.Pad

    @property
    def ThermalPad(self):
        return self.obj.ThermalPad

    @property
    def AntiPad(self):
        return self.obj.AntiPad

    @property
    def Name(self):
        return self.obj.Name

