# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBTextBase(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def LineWidth(self):
        return self.obj.LineWidth

    @property
    def PositionX(self):
        return self.obj.PositionX

    @LineWidth.setter
    def LineWidth(self, LineWidth):
        self.obj.LineWidth=LineWidth

    @property
    def PositionY(self):
        return self.obj.PositionY

    @PositionX.setter
    def PositionX(self, PositionX):
        self.obj.PositionX=PositionX

    @property
    def Height(self):
        return self.obj.Height

    @PositionY.setter
    def PositionY(self, PositionY):
        self.obj.PositionY=PositionY

    @property
    def Mirror(self):
        return self.obj.Mirror

    @Height.setter
    def Height(self, Height):
        self.obj.Height=Height

    @property
    def Orientation(self):
        return self.obj.Orientation

    @Mirror.setter
    def Mirror(self, Mirror):
        self.obj.Mirror=Mirror

    @property
    def HorzJustification(self):
        return self.obj.HorzJustification

    @Orientation.setter
    def Orientation(self, Orientation):
        self.obj.Orientation=Orientation

    @property
    def VertJustification(self):
        return self.obj.VertJustification

    @HorzJustification.setter
    def HorzJustification(self, HorzJustification):
        self.obj.HorzJustification=HorzJustification

    @property
    def layer(self):
        return self.obj.layer

    @VertJustification.setter
    def VertJustification(self, VertJustification):
        self.obj.VertJustification=VertJustification

    @layer.setter
    def layer(self, layer):
        self.obj.layer=layer

