# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBNet(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Name(self):
        return self.obj.Name

    @property
    def selected(self):
        return self.obj.selected

    @selected.setter
    def selected(self, selected):
        self.obj.selected=selected

    @property
    def Highlighted(self):
        return self.obj.Highlighted

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def NetClassAttributes(self):
        return self.obj.NetClassAttributes

    @property
    def Connections(self):
        return self.obj.Connections

    @property
    def Length(self):
        return self.obj.Length

    @property
    def Power(self):
        return self.obj.Power

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def Vias(self):
        return self.obj.Vias

    @property
    def NetClass(self):
        return self.obj.NetClass

    @property
    def Drawings(self):
        return self.obj.Drawings

    @property
    def AssociatedNet(self):
        return self.obj.AssociatedNet

    @Highlighted.setter
    def Highlighted(self, Highlighted):
        self.obj.Highlighted=Highlighted

