# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBCBP(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def Component(self):
        return self.obj.Component

    @property
    def SBPs(self):
        return self.obj.SBPs

    @property
    def Wirebonds(self):
        return self.obj.Wirebonds

    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def Length(self):
        return self.obj.Length

    @property
    def width(self):
        return self.obj.width

    @property
    def Shape(self):
        return self.obj.Shape

    @property
    def Function(self):
        return self.obj.Function

    @property
    def Edge(self):
        return self.obj.Edge

    @property
    def layer(self):
        return self.obj.layer

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Name(self):
        return self.obj.Name

