# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBThermalPad(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def PadStackLayer(self):
        return self.obj.PadStackLayer

    @property
    def Shape(self):
        return self.obj.Shape

    @property
    def InnerSize(self):
        return self.obj.InnerSize

    @property
    def Orientation(self):
        return self.obj.Orientation

    @property
    def offset(self):
        return self.obj.offset

    @property
    def CornerType(self):
        return self.obj.CornerType

    @property
    def CornerRadius(self):
        return self.obj.CornerRadius

    @property
    def InnerLength(self):
        return self.obj.InnerLength

    @property
    def OuterSize(self):
        return self.obj.OuterSize

    @property
    def Spokes(self):
        return self.obj.Spokes

    @property
    def SpokeAngle(self):
        return self.obj.SpokeAngle

    @property
    def SpokeWidth(self):
        return self.obj.SpokeWidth

    @property
    def Name(self):
        return self.obj.Name

