# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBLibrary(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def path(self):
        return self.obj.path

    @property
    def FullName(self):
        return self.obj.FullName

    @property
    def ImportLibraryItems(self):
        return self.obj.ImportLibraryItems

    @property
    def GetLibraryItems(self):
        return self.obj.GetLibraryItems

    @property
    def ImportLibraryItems2(self):
        return self.obj.ImportLibraryItems2

    @property
    def ImportLibraryItemsEncrypted(self):
        return self.obj.ImportLibraryItemsEncrypted

    @property
    def Name(self):
        return self.obj.Name

