# coding=utf-8
"""
This file is autogenerated by python script @ 20200726-10:57:03
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerPCBDrawing(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Name(self):
        return self.obj.Name

    @property
    def selected(self):
        return self.obj.selected

    @property
    def Application(self):
        return self.obj.Application

    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def Net(self):
        return self.obj.Net

    @property
    def Texts(self):
        return self.obj.Texts

    @property
    def DrawingType(self):
        return self.obj.DrawingType

    @property
    def Geometry(self):
        return self.obj.Geometry

    @selected.setter
    def selected(self, selected):
        self.obj.selected=selected

