# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os

__author__ = 'SayCV'



# hlLayerType
# HyperLynx Layer Type Constants.


hlLayerTypeUnknown = 0

hlLayerTypeSignal = 1

hlLayerTypePlane = 2

hlLayerTypeSubstrate = 3

hlLayerTypeSolderMask = 4




# hlScmObjType
# HyperLynx Schematic Object Type Constants.


hlScmObjTypeUnknown = 0

hlScmObjTypeIc = 1

hlScmObjTypeDiffIc = 2

hlScmObjTypeResistor = 3

hlScmObjTypeInductance = 4

hlScmObjTypeCapacitor = 5

hlScmObjTypeFerrBead = 6

hlScmObjTypeTline = 7

hlScmObjTypeGround = 8

hlScmObjTypeVoltage = 9

hlScmObjTypeBlackBox = 10

hlScmObjTypeVia = 11

hlScmObjTypeDiffVia = 12

hlScmObjTypeEntry = 13

hlScmObjTypeMosfet = 14

hlScmObjTypeComment = 15




# hlPadType
# HyperLynx Pad Type constants


hlPadTypeUnknown = 0

hlPadTypePad = 1

hlPadTypeAntipad = 2




# hlPadShape
# HyperLynx Pad Shape constants


hlPadShapeUnknown = 0

hlPadShapeRound = 1

hlPadShapeRectangle = 2

hlPadShapeOval = 3

hlPadShapeOblong = 4

hlPadShapeCustom = 5

hlPadShapeClearance = 6

hlPadShapeNone = 7




# hlTlineType
# HyperLynx T-line Type Constants.


hlTlineTypeUnknown = 0

hlTlineTypeUser = 1

hlTlineTypeAuto = 2




# hlTransmissionLineType
# HyperLynx Transmission Line Type Constants.


hlTLTypeUnknown = 0

hlTLTypeSimple = 1

hlTLTypeStackup = 2

hlTLTypeMicrostrip = 3

hlTLTypeBuriedMicrostrip = 4

hlTLTypeStripline = 5

hlTLTypeWireOverGround = 6

hlTLTypeCable = 7

hlTLTypeConnector = 8

hlTLTypeMicrostripOverHatch = 9

hlTLTypeStriplineBetweenHatch = 10




# hlRefConductorType
# HyperLynx Reference Conductor Type constants


hlRefConductorUnknown = 0

hlRefConductorPlane = 1

hlRefConductorHalfPlaneLeft = 2

hlRefConductorHalfPlaneRight = 3

hlRefConductorTrace = 4

hlRefConductorSpacer = 5

hlRefConductorHatchedPlane = 6




# hlCrosstalkMethod
# HyperLynx Crosstalk Method constants


hlCrosstalkUnknown = 0

hlCrosstalkElectrical = 1

hlCrosstalkGeometric = 2




# hlComponentType
# HyperLynx Component Type Constants.


hlCompTypeUnknown = 0

hlCompTypeIC = 1

hlCompTypeResistor = 2

hlCompTypeCapacitor = 3

hlCompTypeConnector = 4

hlCompTypeInductance = 5

hlCompTypeDiode = 6

hlCompTypeFerrite = 7

hlCompTypeRC = 8

hlCompTypeTestPoint = 9




# hlModelDirType
# HyperLynx Model Direction Type Constants.


hlModDirTypeUnknown = 0

hlModDirTypeInput = 1

hlModDirTypeOutput = 2

hlModDirTypeBidir = 3

hlModDirTypeEnbo = 4

hlModDirTypeSpice = 5




# hlModelIoDirection
# HyperLynx Model I/O Direction Constants.


hlIoDirUnknown = 0

hlIoDirInput = 1

hlIoDirOutput = 2




# hlModelInvertState
# HyperLynx Model Inverted State Constants.


hlInvertStateUnknown = 0

hlInvertStateDirect = 1

hlInvertStateInverted = 2




# hlModelDriverState
# HyperLynx Model Driver State Constants.


hlDrvStateUnknown = 0

hlDrvStateLow = 1

hlDrvStateHigh = 2

hlDrvStateSwitching = 3




# hlBitSequenceType
# HyperLynx Stimulus Bit Sequence Constants.


hlBitSequenceUnknown = 0

hlBitSequenceEdge = 1

hlBitSequenceOscillator = 2

hlBitSequencePBRS = 3

hlBitSequence10B8B = 4

hlBitSequence64B66B = 5

hlBitSequence128B130B = 6

hlBitSequence128B132B = 7




# hlStimInitState
# HyperLynx Stimulus Bit Sequence Constants.


hlStimInitStateUnknown = 0

hlStimInitStateLow = 1

hlStimInitStateHigh = 2




# hlSimType
# HyperLynx Simulator Type constants


hlSimTypeUnknown = 0

hlSimTypeAuto = 1

hlSimTypeHyperSim = 2

hlSimTypeADMS = 3

hlSimTypeHSPICE = 4




# hlSimCorner
# HyperLynx IC condition constants


hlSimCornerUnknown = 0

hlSimCornerWorst = 1

hlSimCornerTypical = 2

hlSimCornerBest = 4




# hlSimOperation
# HyperLynx Simulation Operation constants


hlSimOpUnknown = 0

hlSimOpStandard = 1

hlSimOpEyeDiagram = 2




# hlSimResultTarget
# HyperLynx SimResult waveform view target


hlSimResultTargetOscilloscope = 0

hlSimResultTargetEZWave = 1




# hlFreqSweepType
# HyperLynx Frequency-sweeping constants.


hlFreqSweepUnknown = 0

hlFreqSweepLinear = 1

hlFreqSweepLog = 2

hlFreqSweepAdaptive = 3




# hlFreqSweepTolerance
# HyperLynx Frequency-sweeping Tolerance constants.


hlFreqSweepToleranceUnknown = 0

hlFreqSweepToleranceLow = 1

hlFreqSweepToleranceMedium = 2

hlFreqSweepToleranceHigh = 3




# hlSerDesWizardMode
# HyperLynx SerDes Wizard mode constants


hlSerDesWizardModeFull = 0

hlSerDesWizardModeCompliance = 1

hlSerDesWizardModeMeasured = 2




# hlDrawStyle
# HyperLynx Draw Style Constants.


hlDrawStyleNone = 0

hlDrawStyleHatched = 1

hlDrawStyleSolid = 2

hlDrawStyleOutline = 3




# hlLayerTechnologyType
# HyperLynx Layer Technology Constants.


hlTechnologyPrepreg = 0

hlTechnologyCore = 1

hlTechnologyFlexCore = 2




# hlLayerSide
# HyperLynx Layer Side Constants.


hlLayerSideNone = 0

hlLayerSideTop = 1

hlLayerSideBottom = 2

hlLayerSideBoth = 3




# hlLayerPosition
# HyperLynx Layer Position constants


hlLayerPosUnknown = 0

hlLayerPosTopmost = 1

hlLayerPosBottommost = 2




# hlModelPortConnType
# HyperLynx Model Port connection type constants.


hlModelPortConnUnknown = 0

hlModelPortConnSchem = 1

hlModelPortConnUser = 2




# hlSideType
# HyperLynx Side constants.


hlSideUnknown = 0

hlSideLeft = 1

hlSideRight = 2



