# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHL3DArea(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Name(self):
        return self.obj.Name

    @property
    def OutputFile(self):
        return self.obj.OutputFile

    @Name.setter
    def Name(self, Name):
        self.obj.Name=Name

    @property
    def ModelFile(self):
        return self.obj.ModelFile

    @OutputFile.setter
    def OutputFile(self, OutputFile):
        self.obj.OutputFile=OutputFile

    @property
    def Active(self):
        return self.obj.Active

    @ModelFile.setter
    def ModelFile(self, ModelFile):
        self.obj.ModelFile=ModelFile

    @property
    def Nets(self):
        return self.obj.Nets

    @property
    def PortCount(self):
        return self.obj.PortCount

    @property
    def Solve(self):
        return self.obj.Solve

    @Active.setter
    def Active(self, Active):
        self.obj.Active=Active

