# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLApplication(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def NewSchematic(self):
        return self.obj.NewSchematic

    @property
    def Print(self):
        return self.obj.Print

    @property
    def Exit(self):
        return self.obj.Exit

    @property
    def Design(self):
        return self.obj.Design

    @property
    def Schematic(self):
        return self.obj.Schematic

    @property
    def Simulator(self):
        return self.obj.Simulator

    @property
    def SParamExtractor(self):
        return self.obj.SParamExtractor

    @property
    def Visible(self):
        return self.obj.Visible

    @property
    def OpenFile(self):
        return self.obj.OpenFile

    @property
    def FileName(self):
        return self.obj.FileName

    @property
    def SerDesWizard(self):
        return self.obj.SerDesWizard

    @Visible.setter
    def Visible(self, Visible):
        self.obj.Visible=Visible

