# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLBackdrill(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Setback(self):
        return self.obj.Setback

    @property
    def ToLayer(self):
        return self.obj.ToLayer

    @property
    def Diameter(self):
        return self.obj.Diameter

