# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLCoupling(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Name(self):
        return self.obj.Name

    @property
    def Length(self):
        return self.obj.Length

    @Name.setter
    def Name(self, Name):
        self.obj.Name=Name

    @property
    def TLines(self):
        return self.obj.TLines

    @property
    def Include(self):
        return self.obj.Include

    @property
    def Exclude(self):
        return self.obj.Exclude

    @property
    def GetPos(self):
        return self.obj.GetPos

    @property
    def SetPos(self):
        return self.obj.SetPos

    @property
    def GetRightSeparation(self):
        return self.obj.GetRightSeparation

    @property
    def SetRightSeparation(self):
        return self.obj.SetRightSeparation

    @property
    def GetLeftSeparation(self):
        return self.obj.GetLeftSeparation

    @property
    def SetLeftSeparation(self):
        return self.obj.SetLeftSeparation

    @property
    def FindTLine(self):
        return self.obj.FindTLine

    @property
    def AddRefConductor(self):
        return self.obj.AddRefConductor

    @property
    def DelRefConductor(self):
        return self.obj.DelRefConductor

    @property
    def RefConductors(self):
        return self.obj.RefConductors

    @Length.setter
    def Length(self, Length):
        self.obj.Length=Length

