# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLCollection(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Item(self):
        return self.obj.Item

    @property
    def _NewEnum(self):
        return self.obj._NewEnum

    @property
    def Count(self):
        return self.obj.Count

