# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLCrosstalkSettings(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Threshold(self):
        return self.obj.Threshold

    @property
    def MaxDistToAggressor(self):
        return self.obj.MaxDistToAggressor

    @property
    def MinCoupleSegLen(self):
        return self.obj.MinCoupleSegLen

    @property
    def HorzNeighborLim(self):
        return self.obj.HorzNeighborLim

    @property
    def VertNeighborLim(self):
        return self.obj.VertNeighborLim

    @property
    def SetElectrical(self):
        return self.obj.SetElectrical

    @property
    def SetGeometric(self):
        return self.obj.SetGeometric

    @property
    def Method(self):
        return self.obj.Method

