# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLDbVia(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def y(self):
        return self.obj.y

    @property
    def DrillSize(self):
        return self.obj.DrillSize

    @property
    def Padstack(self):
        return self.obj.Padstack

    @property
    def TopLayer(self):
        return self.obj.TopLayer

    @property
    def BottomLayer(self):
        return self.obj.BottomLayer

    @property
    def ConnectedLayers(self):
        return self.obj.ConnectedLayers

    @property
    def GetBackdrill(self):
        return self.obj.GetBackdrill

    @property
    def ClearBackdrill(self):
        return self.obj.ClearBackdrill

    @property
    def SetBackdrill(self):
        return self.obj.SetBackdrill

    @property
    def Stackup(self):
        return self.obj.Stackup

    @property
    def x(self):
        return self.obj.x

