# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLFabrication(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Technology(self):
        return self.obj.Technology

    @property
    def RoughnessTop(self):
        return self.obj.RoughnessTop

    @Technology.setter
    def Technology(self, Technology):
        self.obj.Technology=Technology

    @property
    def RoughnessBottom(self):
        return self.obj.RoughnessBottom

    @RoughnessTop.setter
    def RoughnessTop(self, RoughnessTop):
        self.obj.RoughnessTop=RoughnessTop

    @property
    def TrapNarrowSide(self):
        return self.obj.TrapNarrowSide

    @RoughnessBottom.setter
    def RoughnessBottom(self, RoughnessBottom):
        self.obj.RoughnessBottom=RoughnessBottom

    @property
    def TrapEtchFactor(self):
        return self.obj.TrapEtchFactor

    @TrapNarrowSide.setter
    def TrapNarrowSide(self, TrapNarrowSide):
        self.obj.TrapNarrowSide=TrapNarrowSide

    @TrapEtchFactor.setter
    def TrapEtchFactor(self, TrapEtchFactor):
        self.obj.TrapEtchFactor=TrapEtchFactor

