# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLScmDiffVia(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def MaxConnectedLayers(self):
        return self.obj.MaxConnectedLayers

    @property
    def Padstack(self):
        return self.obj.Padstack

    @MaxConnectedLayers.setter
    def MaxConnectedLayers(self, MaxConnectedLayers):
        self.obj.MaxConnectedLayers=MaxConnectedLayers

    @property
    def Stackup(self):
        return self.obj.Stackup

    @Padstack.setter
    def Padstack(self, Padstack):
        self.obj.Padstack=Padstack

    @Stackup.setter
    def Stackup(self, Stackup):
        self.obj.Stackup=Stackup

