# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLScmBlackBox(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Model(self):
        return self.obj.Model

    @property
    def ModelPorts(self):
        return self.obj.ModelPorts

    @property
    def AssignModel(self):
        return self.obj.AssignModel

