# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLSchematic(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Objects(self):
        return self.obj.Objects

    @property
    def Nets(self):
        return self.obj.Nets

    @property
    def Stackup(self):
        return self.obj.Stackup

    @property
    def Stackups(self):
        return self.obj.Stackups

    @property
    def Couplings(self):
        return self.obj.Couplings

    @property
    def SimSettings(self):
        return self.obj.SimSettings

    @property
    def Padstacks(self):
        return self.obj.Padstacks

    @property
    def SupplyNets(self):
        return self.obj.SupplyNets

    @property
    def AddObject(self):
        return self.obj.AddObject

    @property
    def FindObject(self):
        return self.obj.FindObject

    @property
    def GetNet(self):
        return self.obj.GetNet

    @property
    def AddPadstack(self):
        return self.obj.AddPadstack

    @property
    def FindPadstack(self):
        return self.obj.FindPadstack

    @property
    def DeletePadstack(self):
        return self.obj.DeletePadstack

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def Connect(self):
        return self.obj.Connect

    @property
    def Disconnect(self):
        return self.obj.Disconnect

    @property
    def CreateCoupling(self):
        return self.obj.CreateCoupling

    @property
    def DiscardCoupling(self):
        return self.obj.DiscardCoupling

    @property
    def FindCoupling(self):
        return self.obj.FindCoupling

    @property
    def AutoPlace(self):
        return self.obj.AutoPlace

    @property
    def Save(self):
        return self.obj.Save

    @property
    def FindStackup(self):
        return self.obj.FindStackup

    @property
    def CreateStackup(self):
        return self.obj.CreateStackup

    @property
    def DeleteStackup(self):
        return self.obj.DeleteStackup

    @property
    def AddSupplyNet(self):
        return self.obj.AddSupplyNet

    @property
    def DeleteSupplyNet(self):
        return self.obj.DeleteSupplyNet

    @property
    def FindSupplyNet(self):
        return self.obj.FindSupplyNet

    @property
    def Viewer(self):
        return self.obj.Viewer

