# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLSimulator(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Type(self):
        return self.obj.Type

    @property
    def Stimulus(self):
        return self.obj.Stimulus

    @property
    def Corner(self):
        return self.obj.Corner

    @Type.setter
    def Type(self, Type):
        self.obj.Type=Type

    @property
    def StopAuto(self):
        return self.obj.StopAuto

    @Corner.setter
    def Corner(self, Corner):
        self.obj.Corner=Corner

    @property
    def StopTime(self):
        return self.obj.StopTime

    @StopAuto.setter
    def StopAuto(self, StopAuto):
        self.obj.StopAuto=StopAuto

    @property
    def StepAuto(self):
        return self.obj.StepAuto

    @StopTime.setter
    def StopTime(self, StopTime):
        self.obj.StopTime=StopTime

    @property
    def Step(self):
        return self.obj.Step

    @StepAuto.setter
    def StepAuto(self, StepAuto):
        self.obj.StepAuto=StepAuto

    @property
    def Operation(self):
        return self.obj.Operation

    @Step.setter
    def Step(self, Step):
        self.obj.Step=Step

    @property
    def Run(self):
        return self.obj.Run

    @property
    def Result(self):
        return self.obj.Result

    @property
    def Target(self):
        return self.obj.Target

    @Operation.setter
    def Operation(self, Operation):
        self.obj.Operation=Operation

    @Target.setter
    def Target(self, Target):
        self.obj.Target=Target

