# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLSimResult(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Show(self):
        return self.obj.Show

    @property
    def FindWaveform(self):
        return self.obj.FindWaveform

    @property
    def Waveforms(self):
        return self.obj.Waveforms

