# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicSheet(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Name(self):
        return self.obj.Name

    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def ChildSheets(self):
        return self.obj.ChildSheets

    @property
    def ParentSheet(self):
        return self.obj.ParentSheet

    @property
    def Gates(self):
        return self.obj.Gates

    @property
    def Nets(self):
        return self.obj.Nets

    @property
    def Components(self):
        return self.obj.Components

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def Activate(self):
        return self.obj.Activate

    @property
    def GetObjects(self):
        return self.obj.GetObjects

    @property
    def AddGate(self):
        return self.obj.AddGate

    @property
    def AddComponent(self):
        return self.obj.AddComponent

    @property
    def PartTypes(self):
        return self.obj.PartTypes

    @Name.setter
    def Name(self, Name):
        self.obj.Name=Name

