# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicDoc(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def FullName(self):
        return self.obj.FullName

    @property
    def Path(self):
        return self.obj.Path

    @property
    def Saved(self):
        return self.obj.Saved

    @property
    def Name(self):
        return self.obj.Name

    @property
    def ActiveView(self):
        return self.obj.ActiveView

    @property
    def ActiveSheet(self):
        return self.obj.ActiveSheet

    @property
    def Sheets(self):
        return self.obj.Sheets

    @property
    def AncestorSheets(self):
        return self.obj.AncestorSheets

    @property
    def Components(self):
        return self.obj.Components

    @property
    def Nets(self):
        return self.obj.Nets

    @property
    def Gates(self):
        return self.obj.Gates

    @Saved.setter
    def Saved(self, Saved):
        self.obj.Saved=Saved

    @property
    def GridX(self):
        return self.obj.GridX

    @GridX.setter
    def GridX(self, GridX):
        self.obj.GridX=GridX

    @property
    def GridY(self):
        return self.obj.GridY

    @property
    def OriginX(self):
        return self.obj.OriginX

    @property
    def OriginY(self):
        return self.obj.OriginY

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def Activate(self):
        return self.obj.Activate

    @property
    def ExportASCII(self):
        return self.obj.ExportASCII

    @property
    def ExportNetList(self):
        return self.obj.ExportNetList

    @property
    def GenerateECO(self):
        return self.obj.GenerateECO

    @property
    def GetObjects(self):
        return self.obj.GetObjects

    @property
    def Import(self):
        return self.obj.Import

    @property
    def ImportASCII(self):
        return self.obj.ImportASCII

    @property
    def ImportECO(self):
        return self.obj.ImportECO

    @property
    def Save(self):
        return self.obj.Save

    @property
    def SaveAs(self):
        return self.obj.SaveAs

    @property
    def SelectObjects(self):
        return self.obj.SelectObjects

    @property
    def PartTypes(self):
        return self.obj.PartTypes

    @property
    def AttributeTypes(self):
        return self.obj.AttributeTypes

    @property
    def Fields(self):
        return self.obj.Fields

    @property
    def SaveTemp(self):
        return self.obj.SaveTemp

    @property
    def SaveAsTemp(self):
        return self.obj.SaveAsTemp

    @property
    def SaveNoLock(self):
        return self.obj.SaveNoLock

    @property
    def SaveAsNoLock(self):
        return self.obj.SaveAsNoLock

    @property
    def IntegrityTest(self):
        return self.obj.IntegrityTest

    @property
    def SetColor(self):
        return self.obj.SetColor

    @property
    def GetColor(self):
        return self.obj.GetColor

    @GridY.setter
    def GridY(self, GridY):
        self.obj.GridY=GridY

