# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicPin(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def GatePinName(self):
        return self.obj.GatePinName

    @property
    def Number(self):
        return self.obj.Number

    @property
    def Gate(self):
        return self.obj.Gate

    @property
    def Net(self):
        return self.obj.Net

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def selected(self):
        return self.obj.selected

    @property
    def Name(self):
        return self.obj.Name

    @property
    def FunctionName(self):
        return self.obj.FunctionName

    @property
    def ElectricalType(self):
        return self.obj.ElectricalType

    @property
    def SwapClass(self):
        return self.obj.SwapClass

    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def Component(self):
        return self.obj.Component

    @property
    def AlphaNumber(self):
        return self.obj.AlphaNumber

    @selected.setter
    def selected(self, selected):
        self.obj.selected=selected

