# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicFields(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def _NewEnum(self):
        return self.obj._NewEnum

    @property
    def Count(self):
        return self.obj.Count

    @property
    def Add(self):
        return self.obj.Add

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def Item(self):
        return self.obj.Item

