# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicNet(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def Width(self):
        return self.obj.Width

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def selected(self):
        return self.obj.selected

    @property
    def Name(self):
        return self.obj.Name

    @property
    def Sheets(self):
        return self.obj.Sheets

    @property
    def Attributes(self):
        return self.obj.Attributes

    @selected.setter
    def selected(self, selected):
        self.obj.selected=selected

