# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-11:53:05
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IPowerLogicView(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Application(self):
        return self.obj.Application

    @property
    def Parent(self):
        return self.obj.Parent

    @property
    def TopLeftX(self):
        return self.obj.TopLeftX

    @property
    def TopLeftY(self):
        return self.obj.TopLeftY

    @property
    def BottomRightX(self):
        return self.obj.BottomRightX

    @property
    def BottomRightY(self):
        return self.obj.BottomRightY

    @property
    def PointerX(self):
        return self.obj.PointerX

    @property
    def PointerY(self):
        return self.obj.PointerY

    @property
    def Refresh(self):
        return self.obj.Refresh

    @property
    def Pan(self):
        return self.obj.Pan

    @property
    def SetExtentsToAll(self):
        return self.obj.SetExtentsToAll

    @property
    def SetExtentsToSheet(self):
        return self.obj.SetExtentsToSheet

    @property
    def SetExtents(self):
        return self.obj.SetExtents

    @property
    def Name(self):
        return self.obj.Name

