# coding=utf-8
"""
This file is autogenerated by python script @ 20200810-20:11:30
"""

__author__ = 'SayCV'

from .hldrc import *

from .hyperlynx import *

from .padspcb import *

from .padssch import *

import win32com.client
import pythoncom

class mputils(object):
    def __init__(self):
        self.client = None
    
    def HLDRCApplication(self):
        try:
            self.client = win32com.client.Dispatch("HLDRC.HLApplication")
        except pythoncom.com_error as e:
            print(e)
            raise Exception("Invalid client application!")
        return self.client

    def HLApplication(self):
        try:
            self.client = win32com.client.Dispatch("HyperLynx.HLApplication")
        except pythoncom.com_error as e:
            print(e)
            raise Exception("Invalid client application!")
        return self.client

    def PADSPCBApplication(self):
        try:
            self.client = win32com.client.Dispatch("PowerPCB.Application")
        except pythoncom.com_error as e:
            print(e)
            raise Exception("Invalid client application!")
        return self.client

    def PADSSCHApplication(self):
        try:
            self.client = win32com.client.Dispatch("PowerLogic.Application")
            #self.client.Visible = True
        except pythoncom.com_error as e:
            print(e)
            raise Exception("Invalid client application!")
        return self.client

