# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os

__author__ = 'SayCV'



# drcObjectType
# HyperLynx DRC Object Types Constants.


drcObjectTypeApplication = 0

drcObjectTypeDocument = 1

drcObjectTypeView = 2

drcObjectTypeGUI = 3

drcObjectTypeDrawing = 4

drcObjectTypeDisplayControl = 5

drcObjectTypeGeomEngine = 6

drcObjectTypePathFinder = 7

drcObjectTypeFormat = 8

drcObjectTypeCollection = 9

drcObjectTypeGeometry = 10

drcObjectTypeExtrema = 11

drcObjectTypeAreaFill = 12

drcObjectTypeCouplingAssignment = 13

drcObjectTypeCouplingElement = 14

drcObjectTypeLayerStackup = 15

drcObjectTypePackageModel = 16

drcObjectTypePathSection = 17

drcObjectTypeSeriesPairData = 18

drcObjectTypeDifferentialPairData = 19

drcObjectTypePinDeviceModel = 20

drcObjectTypePackagePinModel = 21

drcObjectTypeVector = 22

drcObjectTypeViolation = 23

drcObjectTypeViolationType = 24

drcObjectTypeNativeDBCollection = 25

drcObjectTypeCollEngine = 26

drcObjectTypeDBObjectCollection = 27

drcObjectTypeEnclosureSlotGroup = 28

drcObjectTypeGeometries = 29

drcObjectTypeTextReport = 30

drcObjectTypeTestPoint = 31

drcObjectTypeHole = 32

drcObjectTypeConductiveText = 33

drcObjectTypeAttribute = 34

drcObjectTypeComponent = 35

drcObjectTypePhysicalNet = 36

drcObjectTypeElectricalNet = 37

drcObjectTypePin = 38

drcObjectTypeVia = 39

drcObjectTypeUnroutedSegment = 40

drcObjectTypeAnnotation = 41

drcObjectTypeNetClass = 42

drcObjectTypeObjectList = 43

drcObjectTypeRuleParam = 44

drcObjectTypeBoard = 45

drcObjectTypeLayer = 46

drcObjectTypePad = 47

drcObjectTypeCompModel = 48

drcObjectTypeEnclosureModel = 49

drcObjectTypeTrace = 50

drcObjectTypeSegment = 51

drcObjectTypeCompPinModel = 52

drcObjectTypePath = 53

drcObjectTypeRule = 54

drcObjectTypeMeasureEngine = 55

drcObjectTypeSchBus = 56

drcObjectTypeSchPin = 57

drcObjectTypeSchNet = 58

drcObjectTypeSchComponent = 59

drcObjectTypeSchPort = 60

drcObjectTypeSchematic = 61

drcObjectTypeSchText = 62

drcObjectTypeSchSheet = 63

drcObjectTypeMeasureCheckSet = 64

drcObjectTypeContour = 65

drcObjectTypeCrossSection = 66

drcObjectTypeCrossSegment = 67

drcObjectTypeTransLine = 68

drcObjectTypeSolderMask = 69

drcObjectTypeSolderPaste = 70

drcObjectTypeMeasureGeomSet = 71

drcObjectTypeFiducial = 72

drcObjectTypeSetupWizard = 73

drcObjectTypeElecNetDiffPair = 74

drcObjectTypeTeardrop = 75

drcObjectTypeCrossSectionBuilder = 76

drcObjectTypeFieldSolver = 77

drcObjectTypeModelIndex = 78

drcObjectTypeViolationGroup = 79

drcObjectTypeObjectStorage = 80

drcObjectTypeShareList = 81

drcObjectTypeMeasureHazard = 82

drcObjectTypeMeasureRule = 83

drcObjectTypePicture = 84

drcObjectTypeMountingHole = 85

drcObjectTypeWelcomeScreen = 86

drcObjectTypeBackDrilling = 87

drcObjectTypeSettings = 88

drcObjectTypeGraph = 89

drcObjectTypeGraphNode = 90

drcObjectTypeGraphEdge = 91

drcObjectTypeGraphEngine = 92

drcObjectTypeGraphShortestPath = 93

drcObjectTypeFilter = 94

drcObjectTypeConditionGroup = 95

drcObjectTypePropertyCondition = 96

drcObjectTypeNetPairCondition = 97

drcObjectTypeAttributeCondition = 98

drcObjectTypePresentation = 99

drcObjectTypeCompModelSelector = 100

drcObjectTypeConstraintClass = 101

drcObjectTypeModelSelector = 102

drcObjectTypeCreepageEngine = 103

drcObjectTypeCreepage = 104

drcObjectTypeText = 105

drcObjectTypeDrawObject = 106

drcObjectTypeBoardRegion = 107

drcObjectTypeCavity = 108

drcObjectTypeBendArea = 109

drcObjectTypeBondFinger = 110

drcObjectTypeBondWire = 111

drcObjectTypeAll = 9999




# HyperLynxDrcColorIndex
# HyperLynx DRC Color Index Constants.


drcColorIndexFirst = 0

drcColorIndexBlack = 0

drcColorIndexNavi = 1

drcColorIndexGreen = 2

drcColorIndexTeal = 3

drcColorIndexMaroon = 4

drcColorIndexPurple = 5

drcColorIndexOlive = 6

drcColorIndexGray = 7

drcColorIndexSilver = 8

drcColorIndexBlue = 9

drcColorIndexLime = 10

drcColorIndexCyan = 11

drcColorIndexRed = 12

drcColorIndexMagenta = 13

drcColorIndexYellow = 14

drcColorIndexWhite = 15

drcColorIndexDarkKhaki = 16

drcColorIndexSteelBlue = 17

drcColorIndexLimeGreen = 18

drcColorIndexMediumTurquoise = 19

drcColorIndexTomato = 20

drcColorIndexMediumPurple = 21

drcColorIndexDarkGoldenrod = 22

drcColorIndexDeepPink = 23

drcColorIndexKhaki = 24

drcColorIndexDodgerBlue = 25

drcColorIndexMediumSeaGreen = 26

drcColorIndexPaleTurquoise = 27

drcColorIndexPink = 28

drcColorIndexThistle = 29

drcColorIndexSandyBrown = 30

drcColorIndexHotPink = 31

drcColorIndexLast = 31




# HyperLynxDrcFontStyle
# HyperLynx DRC Font Style Constants.


drcFontStyleBold = 1

drcFontStyleItalic = 2

drcFontStyleUnderline = 4

drcFontStyleStrikeOut = 8




# HyperLynxDrcAngleUnitType
# HyperLynx DRC Angle Unit Constants.


drcAngleUnitAutomatic = 0

drcAngleUnitDegree = 1

drcAngleUnitRadian = 2




# HyperLynxDrcDistanceUnitType
# HyperLynx DRC Distance Unit Constants.


drcDistanceUnitAutomatic = 0

drcDistanceUnitMil = 1

drcDistanceUnitInch = 2

drcDistanceUnitMillimeter = 3

drcDistanceUnitMicron = 4

drcDistanceUnitMeter = 5

drcDistanceUnitNanometer = 6




# HyperLynxDrcVoltageUnitType
# HyperLynx DRC Voltage Unit Constants.


drcVoltageUnitAutomatic = 0

drcVoltageUnitVolt = 1

drcVoltageUnitMillivolt = 2

drcVoltageUnitMicrovolt = 3

drcVoltageUnitNanovolt = 4




# HyperLynxDrcCapacitanceUnitType
# HyperLynx DRC Capacitance Unit Constants.


drcCapacitanceUnitAutomatic = 0

drcCapacitanceUnitPicofarad = 1

drcCapacitanceUnitNanofarad = 2

drcCapacitanceUnitMicrofarad = 3

drcCapacitanceUnitMillifarad = 4

drcCapacitanceUnitFarad = 5




# HyperLynxDrcResistanceUnitType
# HyperLynx DRC Resistance Unit Constants.


drcResistanceUnitAutomatic = 0

drcResistanceUnitOhm = 1

drcResistanceUnitMilliohm = 2

drcResistanceUnitKiloohm = 3

drcResistanceUnitMegaohm = 4

drcResistanceUnitGigaohm = 5




# HyperLynxDrcInductanceUnitType
# HyperLynx DRC Inductance Unit Constants.


drcInductanceUnitAutomatic = 0

drcInductanceUnitNanohenry = 1

drcInductanceUnitMicrohenry = 2

drcInductanceUnitMillihenry = 3

drcInductanceUnitHenry = 4




# HyperLynxDrcFrequencyUnitType
# HyperLynx DRC Frequency Unit Constants.


drcFrequencyUnitAutomatic = 0

drcFrequencyUnitMegahertz = 1

drcFrequencyUnitGigahertz = 2

drcFrequencyUnitHertz = 3

drcFrequencyUnitKilohertz = 4




# HyperLynxDrcTimeUnitType
# HyperLynx DRC Time Unit Constants.


drcTimeUnitAutomatic = 0

drcTimeUnitPicosecond = 1

drcTimeUnitNanosecond = 2

drcTimeUnitMicrosecond = 3

drcTimeUnitMillisecond = 4

drcTimeUnitSecond = 5




# HyperLynxDrcCurrentUnitType
# HyperLynx DRC Current Unit Constants.


drcCurrentUnitAutomatic = 0

drcCurrentUnitNanoampere = 1

drcCurrentUnitMicroampere = 2

drcCurrentUnitMilliampere = 3

drcCurrentUnitAmpere = 4




# HyperLynxDrcModelIndexLoadStrategy
# HyperLynx DRC Model Index Load Strategy.


drcModelIndexLoadStrategy_UseFirstFound = 0

drcModelIndexLoadStrategy_UseLastFound = 1

drcModelIndexLoadStrategy_UseMostRecent = 2

drcModelIndexLoadStrategy_FailIfConflict = 3




# HyperLynxDrcModelDomain
# HyperLynx DRC Model Domain Constants.


drcModelDomainUnknown = 0

drcModelDomainAnalog = 1

drcModelDomainDigital = 2

drcModelDomainMixed = 3




# HyperLynxDrcSeriesType
# HyperLynx DRC Series Constants.


drcSeriesNone = 0

drcSeriesResistor = 1

drcSeriesCapacitor = 2

drcSeriesInductor = 3

drcSeriesFerrite = 4

drcSeriesDiode = 5




# HyperLynxDrcPinType
# HyperLynx DRC Pin Constants.


drcPinTypeOther = 0

drcPinTypeDriver = 1

drcPinTypeBidirectional = 2

drcPinTypeReceiver = 3

drcPinTypeConnector = 4

drcPinTypeSeries = 5

drcPinTypePower = 6

drcPinTypeVirtual = 7

drcPinTypeGuide = 8




# HyperLynxDrcRadiationClassType
# HyperLynx DRC Radiation Class Constants.


drcRadiationClassUnknown = 0

drcRadiationClassLow = 1

drcRadiationClassMedium = 2

drcRadiationClassHigh = 3




# HyperLynxDrcSusceptibilityClassType
# HyperLynx DRC Susceptibility Class Constants.


drcSusceptibilityClassUnknown = 0

drcSusceptibilityClassLow = 1

drcSusceptibilityClassMedium = 2

drcSusceptibilityClassHigh = 3




# HyperLynxDrcLayerType
# HyperLynx DRC Layer Type Constants.


drcLayerTypeUnknown = 0

drcLayerTypeSignal = 1

drcLayerTypeDielectric = 2

drcLayerTypePlane = 3

drcLayerTypePlaneNegative = 4

drcLayerTypeSplit = 5

drcLayerTypeSilkScreenTop = 6

drcLayerTypeSilkScreenBottom = 7

drcLayerTypeConforming = 8

drcLayerTypeEnvironment = 9

drcLayerTypeSolderMaskTop = 10

drcLayerTypeSolderMaskBottom = 11

drcLayerTypeSolderPasteTop = 12

drcLayerTypeSolderPasteBottom = 13

drcLayerTypeBareDiePad = 14

drcLayerTypeCoverlay = 15

drcLayerTypeAdhesive = 16

drcLayerTypeStiffener = 17




# HyperLynxDrcViolationStatus
# HyperLynx DRC Violation Status Constants.


drcViolationStatusUnassigned = 0

drcViolationStatusToBeReviewed = 0

drcViolationStatusIgnored = 1

drcViolationStatusOKToIgnore = 1

drcViolationStatusApproved = 2

drcViolationStatusToBeFixed = 3

drcViolationStatusFixIfPossible = 3

drcViolationStatusCritical = 4

drcViolationStatusMustFix = 4




# HyperLynxDrcRuleExecOrder
# HyperLynx DRC Rule Execution Order.


drcRuleExecOrderSetup = 0

drcRuleExecOrderPreprocess = 1

drcRuleExecOrderNormal = 2

drcRuleExecOrderPostprocess = 3




# HyperLynxDrcObjectListAppliedType
# HyperLynx DRC Object List Applied Type.


drcObjectListTypeComponent = 0

drcObjectListTypeCompModel = 1

drcObjectListTypeElecNetDiffPair = 2

drcObjectListTypeElectricalNet = 3

drcObjectListTypeEnclosureModel = 4

drcObjectListTypeLayer = 5

drcObjectListTypeNetClass = 6

drcObjectListTypePackageModel = 7

drcObjectListTypePhysicalNet = 8

drcObjectListTypePin = 9

drcObjectListTypePinDeviceModel = 10

drcObjectListTypeViolation = 11

drcObjectListTypeAreaFill = 12

drcObjectListTypeVia = 13

drcObjectListTypeAll = 14

drcObjectListTypeConstraintClass = 15

drcObjectListTypeBondFinger = 16

drcObjectListTypeBondWire = 17

drcObjectListTypeMountingHole = 18




# HyperLynxDrcRuleFlag
# HyperLynx DRC Rule Flag Constants.


drcRuleFlagGroupSource = 1

drcRuleFlagGroupCompiled = 2

drcRuleFlagGroup = 3

drcRuleFlagSource = 4

drcRuleFlagCompiled = 8

drcRuleFlagNonGroup = 12

drcRuleFlagRecursive = 16

drcRuleFlagTopLevel = 32

drcRuleFlagAll = 63




# HyperLynxDrcRuleParameterType
# HyperLynx DRC Rule Parameter Type Attribute Constants.


drcRuleParamString = 0

drcRuleParamInt = 1

drcRuleParamFloat = 2

drcRuleParamBool = 3

drcRuleParamDistance = 11

drcRuleParamAngle = 12

drcRuleParamVoltage = 13

drcRuleParamCapacitance = 14

drcRuleParamResistance = 15

drcRuleParamInductance = 16

drcRuleParamFrequency = 17

drcRuleParamTime = 18

drcRuleParamCurrent = 19

drcRuleParamArea = 20




# HyperLynxDrcViolationSeverity
# HyperLynx DRC Violation Severity Constants.


drcViolationSeverityPassed = 0xffffffff

drcViolationSeverityInformation = 0

drcViolationSeverityWarning = 1

drcViolationSeverityError = 2




# HyperLynxDrcFieldSolverAccuracy
# HyperLynx DRC Field Solver Accuracy Constant.


drcFSAccuracyRoughEstimate = 0

drcFSAccuracyNormal = 1

drcFSAccuracyHighPrecision = 2




# HyperLynxDrcCrossSectionBuilderMode
# HyperLynx DRC Cross Section Builder Mode Constants.


drcCrossSectionUsePlanes = 1

drcCrossSectionUseRefStructs = 2

drcCrossSectionUseCoupling = 3




# HyperLynxDrcStorageValueType
# HyperLynx DRC Object Storage Value Type Constants.


drcStorageValueAuto = 0xffffffff

drcStorageValueString = 0

drcStorageValueInt = 1

drcStorageValueFloat = 2

drcStorageValueBool = 3

drcStorageValueElecNet = 4

drcStorageValuePhysNet = 5

drcStorageValueComp = 6

drcStorageValuePin = 7

drcStorageValueGeometry = 8

drcStorageValueLayer = 9

drcStorageValueAreaFill = 10

drcStorageValueDistance = 11

drcStorageValueAngle = 12

drcStorageValueVoltage = 13

drcStorageValueCapacitance = 14

drcStorageValueResistance = 15

drcStorageValueInductance = 16

drcStorageValueFrequency = 17

drcStorageValueTime = 18

drcStorageValueCurrent = 19

drcStorageValueArea = 20

drcStorageValueVia = 21

drcStorageValueStorage = 22

drcStorageValueElecNetDiffPair = 25

drcStorageValueDispatch = 128




# HyperLynxDrcVisibilityMode
# HyperLynx DRC Visibility Mode Constants.


drcVisibilityModeHide = 0

drcVisibilityModeFilled = 1

drcVisibilityModeOutline = 2

drcVisibilityModeTransparent = 3




# HyperLynxDrcComponentType
# HyperLynx DRC Component Constants.


drcComponentTypeUnknown = 0

drcComponentTypeIC = 1

drcComponentTypeResistor = 2

drcComponentTypeCapacitor = 3

drcComponentTypeInductor = 4

drcComponentTypeFerrite = 5

drcComponentTypeDiode = 6

drcComponentTypeConnector = 7

drcComponentTypeRF = 8

drcComponentTypeJumper = 9

drcComponentTypeTestPoint = 10

drcComponentTypeVirtualPin = 11

drcComponentTypeDrawing = 12

drcComponentTypeMechanical = 13




# HyperLynxDrcTLineType
# HyperLynx DRC TLine Type Constants.


drcTLineTypeUnknown = 0

drcTLineTypeMicrostrip = 1

drcTLineTypeStripline = 2

drcTLineTypeCoplanar = 3

drcTLineTypeCoplanar2 = 4

drcTLineTypeGroundedCoplanar = 5

drcTLineTypeGroundedCoplanar2 = 6




# HyperLynxDrcCrossSectionStatus
# HyperLynx DRC Cross Section Status Constants.


drcCrossSectionStatusOK = 0

drcCrossSectionStatusFSNeeded = 1

drcCrossSectionStatusFSFailed = 2

drcCrossSectionStatusFSNoGround = 3

drcCrossSectionStatusSignalOnPlane = 4

drcCrossSectionStatusBadStackup = 5




# HyperLynxDrcFiducialSide
# HyperLynx DRC Fiducial Side Constants.


drcFiducialSideAll = 0

drcFiducialSideTop = 1

drcFiducialSideTopOrBottom = 2

drcFiducialSideBottom = 3




# HyperLynxDrcElecNetDiffPairSourceType
# HyperLynx DRC Elecrical Net Differential Pair Source Type.


drcElecNetDiffPairSourceLayout = 0

drcElecNetDiffPairSourceCES = 1

drcElecNetDiffPairSourceModel = 2

drcElecNetDiffPairSourceAuto = 3

drcElecNetDiffPairSourceUser = 4




# HyperLynxDrcGraphWeightUnit
# HyperLynx DRC Graph Weight Unit Constants.


drcGraphWeightUnitAsIs = 0

drcGraphWeightUnitDistance = 1

drcGraphWeightUnitVoltage = 2

drcGraphWeightUnitCapacitance = 3

drcGraphWeightUnitResistance = 4

drcGraphWeightUnitInductance = 5

drcGraphWeightUnitFrequency = 6

drcGraphWeightUnitTime = 7

drcGraphWeightUnitCurrent = 8

drcGraphWeightUnitAngle = 9




# HyperLynxDrcFilterObjectType
# HyperLynx DRC Filter Object Type Constants.


drcFilterObjectComponent = 0

drcFilterObjectCompModel = 1

drcFilterObjectElecNetDiffPair = 2

drcFilterObjectElecNetPair = 3

drcFilterObjectElectricalNet = 4

drcFilterObjectEnclosureModel = 5

drcFilterObjectLayer = 6

drcFilterObjectNetClass = 7

drcFilterObjectPackageModel = 8

drcFilterObjectPhysicalNet = 9

drcFilterObjectPin = 10

drcFilterObjectPinDeviceModel = 11

drcFilterObjectViolation = 12

drcFilterObjectTypeAll = 13

drcFilterObjectConstraintClass = 14




# HyperLynxDrcConditionGroupRelation
# HyperLynx DRC Condition Group Relation Constants.


drcConditionGroupAppliedToAny = 0

drcConditionGroupAppliedToAll = 1

drcConditionGroupAll = 2




# HyperLynxDrcFilterObjectTypeProperty
# HyperLynx DRC Filter Object Type Property Constants.


drcFilterObjectComponentRefDes = 0

drcFilterObjectComponentPartName = 1

drcFilterObjectComponentAssumedType = 2

drcFilterObjectComponentComponentTypeSource = 3

drcFilterObjectComponentComponentType = 4

drcFilterObjectComponentSeriesComponent = 5

drcFilterObjectComponentModelID = 6

drcFilterObjectComponentModelLoaded = 7

drcFilterObjectComponentSeriesValue = 8

drcFilterObjectComponentPinCount = 9

drcFilterObjectComponentGndCount = 10

drcFilterObjectComponentMaxFreq = 11

drcFilterObjectComponentHasHeatSink = 12

drcFilterObjectCompModelName = 13

drcFilterObjectCompModelDomain = 14

drcFilterObjectCompModelStatus = 15

drcFilterObjectCompModelFamily = 16

drcFilterObjectCompModelPackage = 17

drcFilterObjectCompModelCpd = 18

drcFilterObjectCompModelDt = 19

drcFilterObjectCompModelIccd = 20

drcFilterObjectElecNetDiffPairName = 21

drcFilterObjectElecNetPairPositiveName = 22

drcFilterObjectElecNetPairNegativeName = 23

drcFilterObjectElectricalNetName = 24

drcFilterObjectElectricalNetNamedByUser = 25

drcFilterObjectElectricalNetConstant = 26

drcFilterObjectElectricalNetClock = 27

drcFilterObjectElectricalNetAssumedType = 28

drcFilterObjectElectricalNetVoltage = 29

drcFilterObjectElectricalNetVoltageSwing = 30

drcFilterObjectElectricalNetLowPower = 31

drcFilterObjectElectricalNetNetClass = 32

drcFilterObjectElectricalNetConstraintClass = 33

drcFilterObjectElectricalNetFrequency = 34

drcFilterObjectElectricalNetSwitchingFrequency = 35

drcFilterObjectElectricalNetKneeFrequency = 36

drcFilterObjectElectricalNetRaiseTime = 37

drcFilterObjectElectricalNetFallTime = 38

drcFilterObjectElectricalNetPinCount = 39

drcFilterObjectElectricalNetConnectorPinsCount = 40

drcFilterObjectElectricalNetViaCount = 41

drcFilterObjectElectricalNetAreaCount = 42

drcFilterObjectElectricalNetMountingHolesCount = 43

drcFilterObjectElectricalNetLength = 44

drcFilterObjectElectricalNetRadiationClass = 45

drcFilterObjectElectricalNetSusceptibilityClass = 46

drcFilterObjectElectricalNetAnalog = 47

drcFilterObjectElectricalNetNoisy = 48

drcFilterObjectElectricalNetSensitive = 49

drcFilterObjectEnclosureModelName = 50

drcFilterObjectEnclosureModelLength = 51

drcFilterObjectEnclosureModelWidth = 52

drcFilterObjectEnclosureModelHeight = 53

drcFilterObjectEnclosureModelQ = 54

drcFilterObjectLayerNumber = 55

drcFilterObjectLayerName = 56

drcFilterObjectLayerLayerType = 57

drcFilterObjectLayerDescription = 58

drcFilterObjectLayerThickness = 59

drcFilterObjectLayerDielectric = 60

drcFilterObjectLayerMagnetic = 61

drcFilterObjectLayerResistivity = 62

drcFilterObjectNetClassName = 63

drcFilterObjectPackageModelName = 64

drcFilterObjectPackageModelPkgThickness = 65

drcFilterObjectPackageModelHeatsink = 66

drcFilterObjectPackageModelHeatsinkWidth = 67

drcFilterObjectPackageModelHeatsinkLength = 68

drcFilterObjectPackageModelHeatsinkThickness = 69

drcFilterObjectPhysicalNetName = 70

drcFilterObjectPhysicalNetNameForElecNet = 71

drcFilterObjectPhysicalNetAssumedType = 72

drcFilterObjectPhysicalNetNetType = 73

drcFilterObjectPhysicalNetElectricalNet = 74

drcFilterObjectPhysicalNetNetClassName = 75

drcFilterObjectPhysicalNetPinCount = 76

drcFilterObjectPhysicalNetViaCount = 77

drcFilterObjectPhysicalNetAreaCount = 78

drcFilterObjectPhysicalNetMountingHoleCount = 79

drcFilterObjectPhysicalNetPathCount = 80

drcFilterObjectPhysicalNetMaxTraceWidth = 81

drcFilterObjectPhysicalNetLength = 82

drcFilterObjectPhysicalNetUnconnected = 83

drcFilterObjectPhysicalNetDriverPinsCount = 84

drcFilterObjectPhysicalNetReceiverPinsCount = 85

drcFilterObjectPhysicalNetBiDirPinsCount = 86

drcFilterObjectPhysicalNetConnectorPinsCount = 87

drcFilterObjectPhysicalNetSeriesPinsCount = 88

drcFilterObjectPhysicalNetPowerPinsCount = 89

drcFilterObjectPinName = 90

drcFilterObjectPinNetName = 91

drcFilterObjectPinCompName = 92

drcFilterObjectPinModelName = 93

drcFilterObjectPinPinType = 94

drcFilterObjectPinVoltage = 95

drcFilterObjectPinFreq = 96

drcFilterObjectPinBDTopDiameter = 97

drcFilterObjectPinBDTopSetback = 98

drcFilterObjectPinBDTopDepth = 99

drcFilterObjectPinBDTopLayer = 100

drcFilterObjectPinBDBottomDiameter = 101

drcFilterObjectPinBDBottomSetback = 102

drcFilterObjectPinBDBottomDepth = 103

drcFilterObjectPinBDBottomLayer = 104

drcFilterObjectPinX = 105

drcFilterObjectPinY = 106

drcFilterObjectPinDeviceModelName = 107

drcFilterObjectPinDeviceModelDeviceType = 108

drcFilterObjectPinDeviceModelDeviceFamily = 109

drcFilterObjectViolationDescription = 110

drcFilterObjectViolationSeverity = 111

drcFilterObjectViolationStatus = 112

drcFilterObjectViolationRank = 113

drcFilterObjectViolationTimestamp = 114

drcFilterObjectViolationNotes = 115

drcFilterObjectViolationRuleName = 116

drcFilterObjectViolationRuleParams = 117

drcFilterObjectTypePropertyAll = 118




# HyperLynxDrcConditionRelation
# HyperLynx DRC Condition Relation Constants.


drcConditionBoolIs = 0

drcConditionEnumIs = 1

drcConditionEnumIsNot = 2

drcConditionNumberIsLessThan = 3

drcConditionNumberIsLessThanOrEqualTo = 4

drcConditionNumberIsGreaterThan = 5

drcConditionNumberIsGreaterThanOrEqualTo = 6

drcConditionNumberIsEqualTo = 7

drcConditionNumberIsNotEqualTo = 8

drcConditionAttrIsAssigned = 9

drcConditionAttrIsNotAssigned = 10

drcConditionStringStartsWith = 11

drcConditionStringEndsWith = 12

drcConditionStringContains = 13

drcConditionStringDoesNotContain = 14

drcConditionStringEqualsTo = 15

drcConditionStringMatchesRegExp = 16

drcConditionStringIsntEqualTo = 17

drcConditionStringDoesnMatchRegExp = 18

drcConditionStringMatchesWildcard = 19

drcConditionStringDoesntMatchWildcard = 20

drcConditionAll = 21

drcConditionStringIsEmpty = 22

drcConditionStringIsNotEmpty = 23




# HyperLynxDrcFilterConditionValidationType
# HyperLynx DRC Filter Condition Validation Constants.


drcFilterConditionValid = 0

drcFilterConditionDeleted = 1

drcFilterConditionInvalidProperty = 2

drcFilterConditionInvalidPropertyRelation = 3

drcFilterConditionInvalidPropertyValue = 4

drcFilterConditionInvalidAttribute = 5

drcFilterConditionInvalidAttributeRelation = 6

drcFilterConditionInvalidAttributeValue = 7

drcFilterConditionInvalidNetPairGroup = 8

drcFilterConditionInvalidNetPairProperty = 9




# HyperLynxDrcMeasureHazardSeverity
# HyperLynx DRC Measure Hazard Threshold Level Constants.


drcMeasureHazardSeveritySevere = 0

drcMeasureHazardSeverityModerate = 1

drcMeasureHazardSeverityWarning = 2




# HyperLynxDrcNetType
# HyperLynx DRC Net Type Constants.


drcNetTypeSignal = 0

drcNetTypePower = 1

drcNetTypeGround = 2

drcNetTypeClock = 3




# HyperLynxDrcImageFileType
# HyperLynx DRC Image File Type Constants.


drcImageFileTypeAuto = 0

drcImageFileTypeJpg = 1

drcImageFileTypeBmp = 2




# HyperLynxDrcAlterGeomFormat
# HyperLynx DRC Alternative Formats for Geometry Description.


drcAlterGeomFormatQEString = 0

drcAlterGeomFormatSysGLFile = 1




# HyperLynxDrcPinSubType
# HyperLynx DRC Pin Subtype Constants.


drcPinSubtypeUnknown = 0

drcPinSubtypeInput = 1

drcPinSubtypeOutput = 2

drcPinSubtypeBiDirectional = 3

drcPinSubtypeTristate = 4

drcPinSubtypeOpenCollector = 5

drcPinSubtypeOpenEmitter = 6

drcPinSubtypePower = 7

drcPinSubtypeGround = 8

drcPinSubtypeNotConnected = 9




# drcPackageGroup
# HyperLynx DRC Package Group Constants.


drcPackageGroupBareDie = 0

drcPackageGroupBGA = 1

drcPackageGroupDIP = 2

drcPackageGroupFlipChip = 3

drcPackageGroupLCC = 4

drcPackageGroupPLCC = 5

drcPackageGroupOther = 6

drcPackageGroupPGA = 7

drcPackageGroupSIP = 8

drcPackageGroupSOIC = 9

drcPackageGroupConnector = 10

drcPackageGroupDiscreteAxial = 11

drcPackageGroupDiscreteChip = 12

drcPackageGroupDiscreteOther = 13

drcPackageGroupDiscreteRadial = 14

drcPackageGroupJumper = 15

drcPackageGroupTestPoint = 16

drcPackageGroupBuried = 17

drcPackageGroupGeneral = 18

drcPackageGroupEdgeConnector = 19

drcPackageGroupRFCicruit = 20

drcPackageGroupReusableCircuit = 21

drcPackageGroupEmbeddedResistor = 22

drcPackageGroupEmbeddedCapacitor = 23

drcPackageGroupRFShape = 24




# drcModelAssignType
# HyperLynx DRC Model Assign Type Constants.


drcModelAssignTypePartname = 1

drcModelAssignTypeAttribute = 2

drcModelAssignTypeCES = 3

drcModelAssignTypeUser = 4




# HyperLynxDrcShortestPathAlgorithm
# HyperLynx DRC Shortest Path Algorithm Constants.


drcShortestPathAlgorithmDijkstra = 0

drcShortestPathAlgorithmBellmanFord = 1

drcShortestPathAlgorithmJohnsonAllPaths = 2

drcShortestPathAlgorithmFloydWarshallAllPaths = 3




# HyperLynxDrcSettingsPropPathsType
# HyperLynx DRC Settings Property Paths Constants.


drcPropParentSettingsPath = 0

drcPropIBISModelDirectories = 1

drcPropLocalModelDirectories = 2

drcPropRulesDirectories = 3

drcPropRulesSourceDirectories = 4

drcPropCommonRulesDirectores = 5

drcPropShareListTemplatesDirectories = 6

drcPropPreserveEnvironmentVariables = 7




# HyperLynxDrcSettingsPropUnitsType
# HyperLynx DRC Settings Property Units Constants.


drcPropDistanceSystem = 0

drcPropDistanceUnit = 1

drcPropDistancePrecision = 2

drcPropAngleUnit = 3

drcPropAnglePrecision = 4

drcPropTimeUnit = 5

drcPropTimePrecision = 6

drcPropVoltageUnit = 7

drcPropVoltagePrecision = 8

drcPropCurrentUnit = 9

drcPropCurrentPrecision = 10

drcPropFrequencyUnit = 11

drcPropFrequencyPrecision = 12

drcPropResistanceUnit = 13

drcPropResistancePrecision = 14

drcPropCapacitanceUnit = 15

drcPropCapacitancePrecision = 16

drcPropInductanceUnit = 17

drcPropInductancePrecision = 18




# HyperLynxDrcSettingsPropGeneralType
# HyperLynx DRC General Settings Property Constants.


drcPropPrerouteFactor = 0

drcPropConvertWideTraceToAreaFills = 1

drcPropMinWideTraceWidth = 2

drcPropModelIndexUpdate = 3

drcPropCalculateMetalLayersErAndLossTangent = 4

drcPropRemoveTracesCoveredByOtherMetal = 5




# HyperLynxDrcSettingsPropDefaultType
# HyperLynx DRC Settings Property Default Values Constants.


drcPropStackupSignalThickness = 0

drcPropStackupInsulatorThickness = 1

drcPropStackupInnerDielectricConstant = 2

drcPropStackupOuterDielectricConstant = 3

drcPropStackupMetalResistivity = 4

drcPropStackupLossTangent = 5

drcPropStackupMagneticConstant = 6

drcPropElecNetFrequency = 7

drcPropElecNetEdgeRate = 8

drcPropElecNetShortCircuitCurrent = 9

drcPropElecNetVoltageSwing = 10

drcPropStackupAutoAddTopEnvLayer = 11

drcPropStackupAutoAddTopEnvDielectric = 12

drcPropStackupAutoAddTopEnvTangent = 13

drcPropStackupAutoAddTopConfLayer = 14

drcPropStackupAutoAddTopConfThickness = 15

drcPropStackupAutoAddTopConfDielectric = 16

drcPropStackupAutoAddTopConfTangent = 17

drcPropStackupAutoAddBottomConfLayer = 18

drcPropStackupAutoAddBottomConfThickness = 19

drcPropStackupAutoAddBottomConfDielectric = 20

drcPropStackupAutoAddBottomConfTangent = 21

drcPropStackupAutoAddBottomEnvLayer = 22

drcPropStackupAutoAddBottomEnvDielectric = 23

drcPropStackupAutoAddBottomEnvTangent = 24

drcPropPhysicalNetFilter = 25

drcPropComponentCustomOutlines = 26

drcPropComponentReplaceOutlinesWithBoundingBox = 27

drcPropComponentOutlinesIncludePlacementOutlines = 28

drcPropStackupEnableTrapezoidalTraces = 29

drcPropStackupEtchFactor = 30

drcPropStackupEnableRoughness = 31

drcPropStackupRoughness = 32




# HyperLynxDrcSettingsPropTransmissionLinesType
# HyperLynx DRC Settings Property Transmission Lines Constants.


drcPropGroundSearchDistance = 0

drcPropMinimumTLineLength = 1




# HyperLynxDrcSettingsPropCouplingType
# HyperLynx DRC Settings Property Coupling Constants.


drcPropMinimumAreaDimension = 0

drcPropShieldingEnabled = 1

drcPropSelfCouplingEnabled = 2

drcPropNonParallelCouplingEnabled = 3

drcPropTraceAngleLimit = 4

drcPropDifferentialCouplingEnabled = 5

drcPropVerticalLayerLimit = 6

drcPropMaximumNumCoupledSegments = 7

drcPropCouplingDistance = 8

drcPropFieldSolverEnabled = 9

drcPropAssumeSolidPlanes = 10




# HyperLynxDrcSettingsPropDifferentialPairsType
# HyperLynx DRC Settings Property Differential Pairs Constants.


drcPropIgnoreLayoutDiffPairs = 0

drcPropNonSeriesWithOppositeBranchOfSameDiffPair = 1

drcPropNonSeriesWithNonDifferentialNet = 2

drcPropCustomDiffPairsBuilderFilter = 3




# HyperLynxDrcSettingsPropModelsType
# HyperLynx DRC Settings Property Models Constants.


drcPropModelAssignmentAssignBy = 0

drcPropModelAssignmentAttributeName = 1




# HyperLynxDrcSettingsPropConstraintManagerType
# HyperLynx DRC Settings Property Constraint Manager Constants.


drcPropConstraintManagerDataImport = 0

drcPropConstraintManagerImportVersion = 1

drcPropConstraintManagerImportProject = 2




# HyperLynxDrcSettingsPropViolationsType
# HyperLynx DRC Settings Property Violations Constants.


drcPropAllowDeletingOfViolations = 0

drcPropEnableGatheringPassedData = 1

drcPropEnableResultsBranches = 2




# HyperLynxDrcSettingsPropShareListsType
# HyperLynx DRC Settings Property Share Lists Constants.


drcPropTemplate = 0

drcPropFileExtension = 1

drcPropProcessor = 2

drcPropCommand = 3

drcPropProcessorTimeOut = 4




# HyperLynxDrcSettingsPropBoardViewerGeneralType
# HyperLynx DRC Settings Property Board Viewer General Constants.


drcPropUseTrueTypeFonts = 0

drcPropAutoStartProjectSetupWizard = 1

drcPropRefDesOutlineSizeRatio = 2

drcPropGridXStep = 3

drcPropGridYStep = 4

drcPropZoomFactor = 5

drcPropZoomMinMargin = 6

drcPropZoomMaxMargin = 7

drcPropAnnotationsColor = 8

drcPropAnnotationsFontName = 9

drcPropAnnotationsFontSize = 10




# HyperLynxDrcSettingsPropBoardViewerInfoTipsType
# HyperLynx DRC Settings Property Board Viewer Info Tips Constants.


drcPropShowInfoTips = 0




# HyperLynxDrcSettingsPropBoardViewerInfoTipsComponentType
# HyperLynx DRC Settings Property Board Viewer Info Tips Component Constants.


drcPropShowModelName = 0

drcPropShowReferenceDesignator = 1

drcPropShowPartType = 2

drcPropShowConnectorStatus = 3

drcPropShowSeriesType = 4




# HyperLynxDrcSettingsPropBoardViewerInfoTipsPinType
# HyperLynx DRC Settings Property Board Viewer Info Tips Pin Constants.


drcPropShowPinModelName = 0

drcPropShowPinName = 1

drcPropShowPinNetName = 2

drcPropShowPinConnectionMap = 3




# HyperLynxDrcSettingsPropBoardViewerInfoTipsViaType
# HyperLynx DRC Settings Property Board Viewer Info Tips Via Constants.


drcPropShowViaName = 0

drcPropShowViaNetName = 1

drcPropShowViaPosition = 2

drcPropShowViaConnectionMap = 3




# HyperLynxDrcSettingsPropBoardViewerInfoTipsMountingHoleType
# HyperLynx DRC Settings Property Board Viewer Info Tips Mounting Hole Constants.


drcPropShowMountingHoleName = 0

drcPropShowMountingNetName = 1

drcPropShowMountingPosition = 2




# HyperLynxDrcSettingsPropBoardViewerInfoTipsSegmentType
# HyperLynx DRC Settings Property Board Viewer Info Tips Segment Constants.


drcPropShowSegmentNetName = 0

drcPropShowSegmentLayer = 1

drcPropShowSegmentLength = 2

drcPropShowSegmentWidth = 3




# HyperLynxDrcSettingsPropBoardViewerInfoTipsAreaFillType
# HyperLynx DRC Settings Property Constants.


drcPropShowAreaFillNetName = 0




# HyperLynxDrcSettingsPropBoardViewerReferenceTextComponentType
# HyperLynx DRC Settings Property Board Viewer Reference Text Component Constants.


drcPropShowTextModelName = 0

drcPropShowTextReferenceDesignator = 1

drcPropShowTextPartType = 2




# HyperLynxDrcSettingsPropBoardViewerReferenceTextPinType
# HyperLynx DRC Settings Property Board Viewer Reference Text Pin Constants.


drcPropShowTextPinName = 0

drcPropShowTextPinModelType = 1




# HyperLynxDrcSettingsPropBoardViewerVisibilityType
# HyperLynx DRC Settings Property Board Viewer Visibility Constants.


drcPropShowUnconnectedPins = 0

drcPropShowUnconnectedPads = 1




# HyperLynxDrcSettingsPropBoardViewerColorsType
# HyperLynx DRC Settings Property Board Viewer Colors Constants.


drcPropDimModeColorIntensity = 0

drcPropMarkComponentsWithoutModels = 1

drcPropMarkProblemNets = 2

drcPropErrorNumberThreshold = 3




# HyperLynxDrcSettingsPropScriptEditorType
# HyperLynx DRC Settings Property Script Editor Constants.


drcPropLineNumbers = 0

drcPropLineNumbersColor = 1

drcPropErrorMarkersColor = 2

drcPropSyntaxHighlightingStatements = 3

drcPropSyntaxHighlightingOperators = 4

drcPropSyntaxHighlightingConstants = 5

drcPropSyntaxHighlightingNames = 6

drcPropSyntaxHighlightingComments = 7




# HyperLynxDrcSettingsPropScriptEditorWatchWindowType
# HyperLynx DRC Settings Property Script Editor Watch Window Constants.


drcPropChangedItemsColor = 0




# HyperLynxDrcSettingsPropOutputWindowType
# HyperLynx DRC Settings Property Output Window Constants.


drcPropLogFileName = 0

drcPropMessageColor = 1

drcPropWarningColor = 2

drcPropErrorColor = 3




# HyperLynxDrcSettingsPropInstalledOptionsType
# HyperLynx DRC Settings Property Installed Options Constants.


drcPropPCBApplication = 0

drcPropSchematicApplication = 1

drcPropCrossLicensing = 2

drcPropLisenseExpirationWarningDays = 3

drcPropShowOptionsDialogOnStartup = 4

drcPropLicensingStatusHyperLynxDRC = 5

drcPropLicensingStatusRunStandardPCBRules = 6

drcPropLicensingStatusRunCustomPCBRules = 7

drcPropLicensingStatusAuthorCustomPCBRules = 8

drcPropLicensingStatusRunStandardSchematicRules = 9

drcPropLicensingStatusRunCustomSchematicRules = 10

drcPropLicensingStatusAuthorCustomSchematicRules = 11

drcPropLicensingStatusShareListGeneration = 12




# HyperLynxDrcContentType
# HyperLynx DRC Content Type Constants.


drcContentAuto = 0

drcContentManual = 1




# HyperLynxDrcComponentTypeSource
# HyperLynx DRC Component Type Source Constants.


drcComponentTypeSourceUndefined = 0

drcComponentTypeSourceLayout = 1

drcComponentTypeSourceConstraintManager = 2

drcComponentTypeSourceModel = 3

drcComponentTypeSourceUser = 4

drcComponentTypeSourceHeuristic = 5

drcComponentTypeSourceConflict = 6




# HyperLynxDrcConditionNarrowSide
# HyperLynx DRC Condition Narrow Side Constants.


drcNarrowSideTop = 0

drcNarrowSideBottom = 1




# HyperLynxDrcBoardRegionType
# HyperLynx DRC Board Region Constants.


drcBoardRegionFlex = 0

drcBoardRegionRigid = 1




# HyperLynxDrcCreepageSimulationStatus
# HyperLynx DRC Creepage Simulation Status Constants.


drcCreepageSimStatusOK = 0

drcCreepageSimStatusLowNetNotFound = 1

drcCreepageSimStatusShortcut = 2

drcCreepageSimStatusUnknown = 3




# HyperLynxDrcBendOriginType
# HyperLynx DRC Bend Origin Constants.


drcBendOriginCenter = 0

drcBendOriginLeft = 1

drcBendOriginRight = 2



