# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcGeometries(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Area(self):
        return self.obj.Area

    @property
    def MetalArea(self):
        return self.obj.MetalArea

    @property
    def Cutouts(self):
        return self.obj.Cutouts

    @property
    def Extrema(self):
        return self.obj.Extrema

