# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcUnroutedSegment(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def FromY(self):
        return self.obj.FromY

    @property
    def FromLayer(self):
        return self.obj.FromLayer

    @property
    def ToX(self):
        return self.obj.ToX

    @property
    def ToY(self):
        return self.obj.ToY

    @property
    def ToLayer(self):
        return self.obj.ToLayer

    @property
    def Net(self):
        return self.obj.Net

    @property
    def FromX(self):
        return self.obj.FromX

