# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcCreepageEngine(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ReachLowNet(self):
        return self.obj.ReachLowNet

    @property
    def HighNets(self):
        return self.obj.HighNets

    @property
    def LowNets(self):
        return self.obj.LowNets

    @property
    def FloatingNets(self):
        return self.obj.FloatingNets

    @property
    def Launch(self):
        return self.obj.Launch

    @ReachLowNet.setter
    def ReachLowNet(self, ReachLowNet):
        self.obj.ReachLowNet=ReachLowNet

