# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcBendArea(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Radius(self):
        return self.obj.Radius

    @property
    def Angle(self):
        return self.obj.Angle

    @property
    def Origin(self):
        return self.obj.Origin

    @property
    def Order(self):
        return self.obj.Order

    @property
    def AreaTolerance(self):
        return self.obj.AreaTolerance

    @property
    def FirstCorner(self):
        return self.obj.FirstCorner

    @property
    def LeftSlideDistance(self):
        return self.obj.LeftSlideDistance

    @property
    def RightSlideDistance(self):
        return self.obj.RightSlideDistance

    @property
    def BindingLength(self):
        return self.obj.BindingLength

    @property
    def Outline(self):
        return self.obj.Outline

