# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcCouplingAssignment(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Elements(self):
        return self.obj.Elements

    @property
    def Distance(self):
        return self.obj.Distance

    @property
    def Angle(self):
        return self.obj.Angle

    @property
    def Capacitance(self):
        return self.obj.Capacitance

    @property
    def Inductance(self):
        return self.obj.Inductance

    @property
    def OtherElement(self):
        return self.obj.OtherElement

    @property
    def CrosstalkVoltageEstimate(self):
        return self.obj.CrosstalkVoltageEstimate

    @property
    def GetCrossSection(self):
        return self.obj.GetCrossSection

    @property
    def Length(self):
        return self.obj.Length

