# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcVector(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def StartX(self):
        return self.obj.StartX

    @property
    def StartY(self):
        return self.obj.StartY

    @StartX.setter
    def StartX(self, StartX):
        self.obj.StartX=StartX

    @property
    def EndX(self):
        return self.obj.EndX

    @StartY.setter
    def StartY(self, StartY):
        self.obj.StartY=StartY

    @property
    def EndY(self):
        return self.obj.EndY

    @EndX.setter
    def EndX(self, EndX):
        self.obj.EndX=EndX

    @property
    def Length(self):
        return self.obj.Length

    @property
    def Rotate(self):
        return self.obj.Rotate

    @property
    def Move(self):
        return self.obj.Move

    @property
    def Add(self):
        return self.obj.Add

    @property
    def Scale(self):
        return self.obj.Scale

    @EndY.setter
    def EndY(self, EndY):
        self.obj.EndY=EndY

