# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcView(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def CenterY(self):
        return self.obj.CenterY

    @property
    def Extrema(self):
        return self.obj.Extrema

    @property
    def Pan(self):
        return self.obj.Pan

    @property
    def SetExtentsToAll(self):
        return self.obj.SetExtentsToAll

    @property
    def SetExtentsToBoard(self):
        return self.obj.SetExtentsToBoard

    @property
    def SetExtentsToSelection(self):
        return self.obj.SetExtentsToSelection

    @property
    def SetExtents(self):
        return self.obj.SetExtents

    @property
    def SetExtentsToExtrema(self):
        return self.obj.SetExtentsToExtrema

    @property
    def GetNewDrawing(self):
        return self.obj.GetNewDrawing

    @property
    def CenterX(self):
        return self.obj.CenterX

