# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcCrossSegment(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Inductance(self):
        return self.obj.Inductance

    @property
    def Object(self):
        return self.obj.Object

    @property
    def StartX(self):
        return self.obj.StartX

    @property
    def StartY(self):
        return self.obj.StartY

    @property
    def EndX(self):
        return self.obj.EndX

    @property
    def EndY(self):
        return self.obj.EndY

    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def Net(self):
        return self.obj.Net

    @property
    def Length(self):
        return self.obj.Length

    @property
    def Z0(self):
        return self.obj.Z0

    @property
    def DCResistance(self):
        return self.obj.DCResistance

    @property
    def SkinResistance(self):
        return self.obj.SkinResistance

    @property
    def PropagationSpeed(self):
        return self.obj.PropagationSpeed

    @property
    def CrosstalkVoltageEstimate(self):
        return self.obj.CrosstalkVoltageEstimate

    @property
    def DielectricConductance(self):
        return self.obj.DielectricConductance

    @property
    def Capacitance(self):
        return self.obj.Capacitance

