# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcRule6(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def AppliedTo(self):
        return self.obj.AppliedTo

    @property
    def BondFingers(self):
        return self.obj.BondFingers

    @property
    def BondWires(self):
        return self.obj.BondWires

    @property
    def MountingHoles(self):
        return self.obj.MountingHoles

    @AppliedTo.setter
    def AppliedTo(self, AppliedTo):
        self.obj.AppliedTo=AppliedTo

