# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPathSection(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def StartX(self):
        return self.obj.StartX

    @property
    def StartY(self):
        return self.obj.StartY

    @property
    def EndX(self):
        return self.obj.EndX

    @property
    def EndY(self):
        return self.obj.EndY

    @property
    def Layer_1(self):
        return self.obj.Layer_1

    @property
    def Layer_2(self):
        return self.obj.Layer_2

    @property
    def Objects(self):
        return self.obj.Objects

    @property
    def IsEqual(self):
        return self.obj.IsEqual

    @property
    def Length(self):
        return self.obj.Length

