# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcEnclosureModel(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Length(self):
        return self.obj.Length

    @property
    def Width(self):
        return self.obj.Width

    @Length.setter
    def Length(self, Length):
        self.obj.Length=Length

    @property
    def Height(self):
        return self.obj.Height

    @Width.setter
    def Width(self, Width):
        self.obj.Width=Width

    @property
    def Q(self):
        return self.obj.Q

    @Height.setter
    def Height(self, Height):
        self.obj.Height=Height

    @property
    def Slots(self):
        return self.obj.Slots

    @Q.setter
    def Q(self, Q):
        self.obj.Q=Q

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @property
    def NewSlot(self):
        return self.obj.NewSlot

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def SetName(self):
        return self.obj.SetName

    @Slots.setter
    def Slots(self, Slots):
        self.obj.Slots=Slots

