# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPinModel(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Signal(self):
        return self.obj.Signal

    @property
    def ComponentModel(self):
        return self.obj.ComponentModel

    @property
    def ClockPin(self):
        return self.obj.ClockPin

    @Signal.setter
    def Signal(self, Signal):
        self.obj.Signal=Signal

    @property
    def PowerPin(self):
        return self.obj.PowerPin

    @ClockPin.setter
    def ClockPin(self, ClockPin):
        self.obj.ClockPin=ClockPin

    @property
    def ClockDivider(self):
        return self.obj.ClockDivider

    @PowerPin.setter
    def PowerPin(self, PowerPin):
        self.obj.PowerPin=PowerPin

    @property
    def Voltage(self):
        return self.obj.Voltage

    @ClockDivider.setter
    def ClockDivider(self, ClockDivider):
        self.obj.ClockDivider=ClockDivider

    @property
    def DeviceModel(self):
        return self.obj.DeviceModel

    @Voltage.setter
    def Voltage(self, Voltage):
        self.obj.Voltage=Voltage

    @property
    def RadiationClass(self):
        return self.obj.RadiationClass

    @DeviceModel.setter
    def DeviceModel(self, DeviceModel):
        self.obj.DeviceModel=DeviceModel

    @property
    def SusceptibilityClass(self):
        return self.obj.SusceptibilityClass

    @RadiationClass.setter
    def RadiationClass(self, RadiationClass):
        self.obj.RadiationClass=RadiationClass

    @property
    def DiffPinPairModels(self):
        return self.obj.DiffPinPairModels

    @property
    def SeriesPinPairModels(self):
        return self.obj.SeriesPinPairModels

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def SetName(self):
        return self.obj.SetName

    @SusceptibilityClass.setter
    def SusceptibilityClass(self, SusceptibilityClass):
        self.obj.SusceptibilityClass=SusceptibilityClass

