# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcCrossSection(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ReferenceSegment(self):
        return self.obj.ReferenceSegment

    @property
    def CrossSegments(self):
        return self.obj.CrossSegments

    @property
    def Homogeneous(self):
        return self.obj.Homogeneous

    @property
    def Status(self):
        return self.obj.Status

    @property
    def SignalCrossSegments(self):
        return self.obj.SignalCrossSegments

    @property
    def ConstCrossSegments(self):
        return self.obj.ConstCrossSegments

    @property
    def TransLine(self):
        return self.obj.TransLine

