# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcComponentModel(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Names(self):
        return self.obj.Names

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def PinModels(self):
        return self.obj.PinModels

    @property
    def DiffPinPairModels(self):
        return self.obj.DiffPinPairModels

    @property
    def SeriesPinPairModels(self):
        return self.obj.SeriesPinPairModels

    @property
    def Components(self):
        return self.obj.Components

    @Names.setter
    def Names(self, Names):
        self.obj.Names=Names

    @property
    def Domain(self):
        return self.obj.Domain

    @Components.setter
    def Components(self, Components):
        self.obj.Components=Components

    @property
    def Cpd(self):
        return self.obj.Cpd

    @Domain.setter
    def Domain(self, Domain):
        self.obj.Domain=Domain

    @property
    def Dt(self):
        return self.obj.Dt

    @Cpd.setter
    def Cpd(self, Cpd):
        self.obj.Cpd=Cpd

    @property
    def Iccd(self):
        return self.obj.Iccd

    @Dt.setter
    def Dt(self, Dt):
        self.obj.Dt=Dt

    @property
    def Family(self):
        return self.obj.Family

    @Iccd.setter
    def Iccd(self, Iccd):
        self.obj.Iccd=Iccd

    @property
    def HasHeatSink(self):
        return self.obj.HasHeatSink

    @property
    def PackageModel(self):
        return self.obj.PackageModel

    @Family.setter
    def Family(self, Family):
        self.obj.Family=Family

    @property
    def IsConnector(self):
        return self.obj.IsConnector

    @PackageModel.setter
    def PackageModel(self, PackageModel):
        self.obj.PackageModel=PackageModel

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def NewPinModel(self):
        return self.obj.NewPinModel

    @property
    def NewDiffPinPairModel(self):
        return self.obj.NewDiffPinPairModel

    @property
    def NewSeriesPinPairModel(self):
        return self.obj.NewSeriesPinPairModel

    @property
    def SetName(self):
        return self.obj.SetName

    @IsConnector.setter
    def IsConnector(self, IsConnector):
        self.obj.IsConnector=IsConnector

