# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcMeasureGeomSet(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def Type(self):
        return self.obj.Type

    @property
    def NetName(self):
        return self.obj.NetName

    @property
    def MeasureGeometry(self):
        return self.obj.MeasureGeometry

