# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcExtrema(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def MaxX(self):
        return self.obj.MaxX

    @property
    def MaxY(self):
        return self.obj.MaxY

    @MaxX.setter
    def MaxX(self, MaxX):
        self.obj.MaxX=MaxX

    @property
    def MinX(self):
        return self.obj.MinX

    @MaxY.setter
    def MaxY(self, MaxY):
        self.obj.MaxY=MaxY

    @property
    def MinY(self):
        return self.obj.MinY

    @MinX.setter
    def MinX(self, MinX):
        self.obj.MinX=MinX

    @property
    def Width(self):
        return self.obj.Width

    @property
    def Height(self):
        return self.obj.Height

    @property
    def IsPointInside(self):
        return self.obj.IsPointInside

    @property
    def Combine(self):
        return self.obj.Combine

    @property
    def Expand(self):
        return self.obj.Expand

    @MinY.setter
    def MinY(self, MinY):
        self.obj.MinY=MinY

