# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcCouplingElement(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Trace(self):
        return self.obj.Trace

    @property
    def StartX(self):
        return self.obj.StartX

    @property
    def StartY(self):
        return self.obj.StartY

    @property
    def EndX(self):
        return self.obj.EndX

    @property
    def EndY(self):
        return self.obj.EndY

    @property
    def Depth(self):
        return self.obj.Depth

    @property
    def Net(self):
        return self.obj.Net

    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def CouplingAssignments(self):
        return self.obj.CouplingAssignments

    @property
    def IsConstant(self):
        return self.obj.IsConstant

    @property
    def TLineType(self):
        return self.obj.TLineType

    @property
    def RefUpperLayer(self):
        return self.obj.RefUpperLayer

    @property
    def RefLowerLayer(self):
        return self.obj.RefLowerLayer

    @property
    def RefUpperDistance(self):
        return self.obj.RefUpperDistance

    @property
    def RefLowerDistance(self):
        return self.obj.RefLowerDistance

    @property
    def RefRightDistance(self):
        return self.obj.RefRightDistance

    @property
    def RefLeftDistance(self):
        return self.obj.RefLeftDistance

    @property
    def TransLine(self):
        return self.obj.TransLine

    @property
    def Length(self):
        return self.obj.Length

