# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcBackDrilling(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Diameter(self):
        return self.obj.Diameter

    @property
    def Depth(self):
        return self.obj.Depth

    @property
    def Setback(self):
        return self.obj.Setback

    @property
    def Layer(self):
        return self.obj.Layer

