# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcAnnotation(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def PosX(self):
        return self.obj.PosX

    @property
    def PosY(self):
        return self.obj.PosY

    @PosX.setter
    def PosX(self, PosX):
        self.obj.PosX=PosX

    @property
    def Text(self):
        return self.obj.Text

    @PosY.setter
    def PosY(self, PosY):
        self.obj.PosY=PosY

    @property
    def Move(self):
        return self.obj.Move

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def SetName(self):
        return self.obj.SetName

    @Text.setter
    def Text(self, Text):
        self.obj.Text=Text

