# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcComponent(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def Orientation(self):
        return self.obj.Orientation

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def Violations(self):
        return self.obj.Violations

    @property
    def PartName(self):
        return self.obj.PartName

    @property
    def ComponentModel(self):
        return self.obj.ComponentModel

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def IsSeries(self):
        return self.obj.IsSeries

    @property
    def IsEmbedded(self):
        return self.obj.IsEmbedded

    @property
    def HasHeatSink(self):
        return self.obj.HasHeatSink

    @property
    def Type(self):
        return self.obj.Type

    @property
    def SeriesValue(self):
        return self.obj.SeriesValue

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @ComponentModel.setter
    def ComponentModel(self, ComponentModel):
        self.obj.ComponentModel=ComponentModel

