# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcObjectList(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def AppliedToType(self):
        return self.obj.AppliedToType

    @property
    def Delete(self):
        return self.obj.Delete

    @AppliedToType.setter
    def AppliedToType(self, AppliedToType):
        self.obj.AppliedToType=AppliedToType

