# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcGUI(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def LogWarning(self):
        return self.obj.LogWarning

    @property
    def LogError(self):
        return self.obj.LogError

    @property
    def SetStatusBarText(self):
        return self.obj.SetStatusBarText

    @property
    def MessageBox(self):
        return self.obj.MessageBox

    @property
    def StartProgress(self):
        return self.obj.StartProgress

    @property
    def EndProgress(self):
        return self.obj.EndProgress

    @property
    def Progress(self):
        return self.obj.Progress

    @property
    def Log(self):
        return self.obj.Log

