# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcDrawing(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def View(self):
        return self.obj.View

    @property
    def OriginX(self):
        return self.obj.OriginX

    @OriginX.setter
    def OriginX(self, OriginX):
        self.obj.OriginX=OriginX

    @property
    def OriginY(self):
        return self.obj.OriginY

    @OriginY.setter
    def OriginY(self, OriginY):
        self.obj.OriginY=OriginY

    @property
    def FillColor(self):
        return self.obj.FillColor

    @FillColor.setter
    def FillColor(self, FillColor):
        self.obj.FillColor=FillColor

    @property
    def LineColor(self):
        return self.obj.LineColor

    @LineColor.setter
    def LineColor(self, LineColor):
        self.obj.LineColor=LineColor

    @property
    def LineWidth(self):
        return self.obj.LineWidth

    @LineWidth.setter
    def LineWidth(self, LineWidth):
        self.obj.LineWidth=LineWidth

    @property
    def CurrentPosX(self):
        return self.obj.CurrentPosX

    @CurrentPosX.setter
    def CurrentPosX(self, CurrentPosX):
        self.obj.CurrentPosX=CurrentPosX

    @property
    def CurrentPosY(self):
        return self.obj.CurrentPosY

    @CurrentPosY.setter
    def CurrentPosY(self, CurrentPosY):
        self.obj.CurrentPosY=CurrentPosY

    @property
    def FontSize(self):
        return self.obj.FontSize

    @FontSize.setter
    def FontSize(self, FontSize):
        self.obj.FontSize=FontSize

    @property
    def FontFace(self):
        return self.obj.FontFace

    @FontFace.setter
    def FontFace(self, FontFace):
        self.obj.FontFace=FontFace

    @property
    def FontStyle(self):
        return self.obj.FontStyle

    @property
    def Show(self):
        return self.obj.Show

    @property
    def Clear(self):
        return self.obj.Clear

    @property
    def MoveTo(self):
        return self.obj.MoveTo

    @property
    def LineTo(self):
        return self.obj.LineTo

    @property
    def Polyline(self):
        return self.obj.Polyline

    @property
    def Polygon(self):
        return self.obj.Polygon

    @property
    def Rect(self):
        return self.obj.Rect

    @property
    def FillRect(self):
        return self.obj.FillRect

    @property
    def Circle(self):
        return self.obj.Circle

    @property
    def FillCircle(self):
        return self.obj.FillCircle

    @property
    def Ellipse(self):
        return self.obj.Ellipse

    @property
    def FillEllipse(self):
        return self.obj.FillEllipse

    @property
    def Arc(self):
        return self.obj.Arc

    @property
    def Text(self):
        return self.obj.Text

    @property
    def GetTextExtent(self):
        return self.obj.GetTextExtent

    @property
    def Marker(self):
        return self.obj.Marker

    @FontStyle.setter
    def FontStyle(self, FontStyle):
        self.obj.FontStyle=FontStyle

