# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPin6(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def SetBackDrillingTop(self):
        return self.obj.SetBackDrillingTop

    @property
    def SetBackDrillingBottom(self):
        return self.obj.SetBackDrillingBottom

    @property
    def LayerStackups(self):
        return self.obj.LayerStackups

