# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcMeasureRule(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Severe(self):
        return self.obj.Severe

    @property
    def CheckSets(self):
        return self.obj.CheckSets

    @property
    def Moderate(self):
        return self.obj.Moderate

    @Severe.setter
    def Severe(self, Severe):
        self.obj.Severe=Severe

    @property
    def Warning(self):
        return self.obj.Warning

    @Moderate.setter
    def Moderate(self, Moderate):
        self.obj.Moderate=Moderate

    @Warning.setter
    def Warning(self, Warning):
        self.obj.Warning=Warning

