# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcComponent7(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Height(self):
        return self.obj.Height

    @property
    def LayerStackups(self):
        return self.obj.LayerStackups

    @Height.setter
    def Height(self, Height):
        self.obj.Height=Height

