# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcObjectList2(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ContentType(self):
        return self.obj.ContentType

    @property
    def Filter(self):
        return self.obj.Filter

    @ContentType.setter
    def ContentType(self, ContentType):
        self.obj.ContentType=ContentType

    @property
    def Description(self):
        return self.obj.Description

    @Filter.setter
    def Filter(self, Filter):
        self.obj.Filter=Filter

    @Description.setter
    def Description(self, Description):
        self.obj.Description=Description

