# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcWelcomeScreen(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def OpenDesign(self):
        return self.obj.OpenDesign

    @property
    def GetRecentFile(self):
        return self.obj.GetRecentFile

    @property
    def ToggleOnStartup(self):
        return self.obj.ToggleOnStartup

    @property
    def StartupEnabled(self):
        return self.obj.StartupEnabled

    @property
    def OpenHelp(self):
        return self.obj.OpenHelp

    @property
    def OpenUrl(self):
        return self.obj.OpenUrl

    @property
    def Links(self):
        return self.obj.Links

    @property
    def NewSettingsFile(self):
        return self.obj.NewSettingsFile

