# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcApplication(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def GUI(self):
        return self.obj.GUI

    @property
    def DisplayControl(self):
        return self.obj.DisplayControl

    @property
    def GeomEngine(self):
        return self.obj.GeomEngine

    @property
    def CollEngine(self):
        return self.obj.CollEngine

    @property
    def Visible(self):
        return self.obj.Visible

    @property
    def Version(self):
        return self.obj.Version

    @property
    def ParentRule(self):
        return self.obj.ParentRule

    @Visible.setter
    def Visible(self, Visible):
        self.obj.Visible=Visible

    @property
    def OpenDocument(self):
        return self.obj.OpenDocument

    @ParentRule.setter
    def ParentRule(self, ParentRule):
        self.obj.ParentRule=ParentRule

