# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPresentation(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Drawing(self):
        return self.obj.Drawing

    @property
    def DisplayControl(self):
        return self.obj.DisplayControl

    @Drawing.setter
    def Drawing(self, Drawing):
        self.obj.Drawing=Drawing

    @property
    def View(self):
        return self.obj.View

    @DisplayControl.setter
    def DisplayControl(self, DisplayControl):
        self.obj.DisplayControl=DisplayControl

    @property
    def HighlightedObjects(self):
        return self.obj.HighlightedObjects

    @View.setter
    def View(self, View):
        self.obj.View=View

    @property
    def ViewPortScaleFactor(self):
        return self.obj.ViewPortScaleFactor

    @HighlightedObjects.setter
    def HighlightedObjects(self, HighlightedObjects):
        self.obj.HighlightedObjects=HighlightedObjects

    @property
    def GetViewPort(self):
        return self.obj.GetViewPort

    @property
    def SetViewPort(self):
        return self.obj.SetViewPort

    @property
    def SetViewPortBy(self):
        return self.obj.SetViewPortBy

    @property
    def AddExtremaToViewPort(self):
        return self.obj.AddExtremaToViewPort

    @property
    def Show(self):
        return self.obj.Show

    @property
    def Hide(self):
        return self.obj.Hide

    @property
    def Merge(self):
        return self.obj.Merge

    @property
    def GetDrawingBoundingBox(self):
        return self.obj.GetDrawingBoundingBox

    @ViewPortScaleFactor.setter
    def ViewPortScaleFactor(self, ViewPortScaleFactor):
        self.obj.ViewPortScaleFactor=ViewPortScaleFactor

