# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcRule3(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Location(self):
        return self.obj.Location

    @property
    def OriginalName(self):
        return self.obj.OriginalName

    @property
    def CopyRule(self):
        return self.obj.CopyRule

