# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcRuleParam(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Value(self):
        return self.obj.Value

    @property
    def Description(self):
        return self.obj.Description

    @property
    def Count(self):
        return self.obj.Count

    @property
    def Item(self):
        return self.obj.Item

    @property
    def _NewEnum(self):
        return self.obj._NewEnum

    @property
    def Delete(self):
        return self.obj.Delete

    @Value.setter
    def Value(self, Value):
        self.obj.Value=Value

