# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPinDeviceModel(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def InputCapacitance(self):
        return self.obj.InputCapacitance

    @property
    def Capacitance(self):
        return self.obj.Capacitance

    @InputCapacitance.setter
    def InputCapacitance(self, InputCapacitance):
        self.obj.InputCapacitance=InputCapacitance

    @property
    def ConnectedToShield(self):
        return self.obj.ConnectedToShield

    @Capacitance.setter
    def Capacitance(self, Capacitance):
        self.obj.Capacitance=Capacitance

    @property
    def Edge(self):
        return self.obj.Edge

    @property
    def FallTime(self):
        return self.obj.FallTime

    @ConnectedToShield.setter
    def ConnectedToShield(self, ConnectedToShield):
        self.obj.ConnectedToShield=ConnectedToShield

    @property
    def RiseTime(self):
        return self.obj.RiseTime

    @FallTime.setter
    def FallTime(self, FallTime):
        self.obj.FallTime=FallTime

    @property
    def Ferrite(self):
        return self.obj.Ferrite

    @RiseTime.setter
    def RiseTime(self, RiseTime):
        self.obj.RiseTime=RiseTime

    @property
    def FMax(self):
        return self.obj.FMax

    @Ferrite.setter
    def Ferrite(self, Ferrite):
        self.obj.Ferrite=Ferrite

    @property
    def FMin(self):
        return self.obj.FMin

    @FMax.setter
    def FMax(self, FMax):
        self.obj.FMax=FMax

    @property
    def Isc(self):
        return self.obj.Isc

    @FMin.setter
    def FMin(self, FMin):
        self.obj.FMin=FMin

    @property
    def IsOscillator(self):
        return self.obj.IsOscillator

    @Isc.setter
    def Isc(self, Isc):
        self.obj.Isc=Isc

    @property
    def Noise(self):
        return self.obj.Noise

    @IsOscillator.setter
    def IsOscillator(self, IsOscillator):
        self.obj.IsOscillator=IsOscillator

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def InputResistance(self):
        return self.obj.InputResistance

    @Noise.setter
    def Noise(self, Noise):
        self.obj.Noise=Noise

    @property
    def SeriesType(self):
        return self.obj.SeriesType

    @InputResistance.setter
    def InputResistance(self, InputResistance):
        self.obj.InputResistance=InputResistance

    @property
    def SeriesValue(self):
        return self.obj.SeriesValue

    @SeriesType.setter
    def SeriesType(self, SeriesType):
        self.obj.SeriesType=SeriesType

    @property
    def Shielded(self):
        return self.obj.Shielded

    @SeriesValue.setter
    def SeriesValue(self, SeriesValue):
        self.obj.SeriesValue=SeriesValue

    @property
    def Type(self):
        return self.obj.Type

    @property
    def VMax(self):
        return self.obj.VMax

    @Shielded.setter
    def Shielded(self, Shielded):
        self.obj.Shielded=Shielded

    @property
    def VMin(self):
        return self.obj.VMin

    @VMax.setter
    def VMax(self, VMax):
        self.obj.VMax=VMax

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def SetName(self):
        return self.obj.SetName

    @VMin.setter
    def VMin(self, VMin):
        self.obj.VMin=VMin

