# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcFieldSolver(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Accuracy(self):
        return self.obj.Accuracy

    @property
    def HomogeneityThreshold(self):
        return self.obj.HomogeneityThreshold

    @Accuracy.setter
    def Accuracy(self, Accuracy):
        self.obj.Accuracy=Accuracy

    @property
    def UseEdgeEffects(self):
        return self.obj.UseEdgeEffects

    @HomogeneityThreshold.setter
    def HomogeneityThreshold(self, HomogeneityThreshold):
        self.obj.HomogeneityThreshold=HomogeneityThreshold

    @property
    def Lossy(self):
        return self.obj.Lossy

    @UseEdgeEffects.setter
    def UseEdgeEffects(self, UseEdgeEffects):
        self.obj.UseEdgeEffects=UseEdgeEffects

    @property
    def DistantGround(self):
        return self.obj.DistantGround

    @Lossy.setter
    def Lossy(self, Lossy):
        self.obj.Lossy=Lossy

    @property
    def Calculate(self):
        return self.obj.Calculate

    @DistantGround.setter
    def DistantGround(self, DistantGround):
        self.obj.DistantGround=DistantGround

