# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcMeasureHazard(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Threshold(self):
        return self.obj.Threshold

    @property
    def Distance(self):
        return self.obj.Distance

    @property
    def Severity(self):
        return self.obj.Severity

    @property
    def Geometry1(self):
        return self.obj.Geometry1

    @property
    def Geometry2(self):
        return self.obj.Geometry2

    @property
    def Point1X(self):
        return self.obj.Point1X

    @property
    def Point1Y(self):
        return self.obj.Point1Y

    @property
    def Point2X(self):
        return self.obj.Point2X

    @property
    def Point2Y(self):
        return self.obj.Point2Y

    @property
    def Rule(self):
        return self.obj.Rule

    @property
    def Layer(self):
        return self.obj.Layer

