# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcMeasureEngine(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ProximityCheck(self):
        return self.obj.ProximityCheck

    @property
    def CreateCheckSet(self):
        return self.obj.CreateCheckSet

    @property
    def Rules(self):
        return self.obj.Rules

