# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcBondFinger(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def IsConnected(self):
        return self.obj.IsConnected

    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def Pads(self):
        return self.obj.Pads

    @property
    def Teardrops(self):
        return self.obj.Teardrops

    @property
    def Orientation(self):
        return self.obj.Orientation

    @property
    def LayerStackups(self):
        return self.obj.LayerStackups

    @property
    def Net(self):
        return self.obj.Net

