# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcElecNet(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def DiffPair(self):
        return self.obj.DiffPair

    @property
    def Violations(self):
        return self.obj.Violations

    @property
    def PhysicalNets(self):
        return self.obj.PhysicalNets

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def Vias(self):
        return self.obj.Vias

    @property
    def Traces(self):
        return self.obj.Traces

    @property
    def AreaFills(self):
        return self.obj.AreaFills

    @property
    def Frequency(self):
        return self.obj.Frequency

    @property
    def RiseTime(self):
        return self.obj.RiseTime

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def FallTime(self):
        return self.obj.FallTime

    @RiseTime.setter
    def RiseTime(self, RiseTime):
        self.obj.RiseTime=RiseTime

    @property
    def IsConstant(self):
        return self.obj.IsConstant

    @property
    def Voltage(self):
        return self.obj.Voltage

    @property
    def Length(self):
        return self.obj.Length

    @property
    def CouplingNets(self):
        return self.obj.CouplingNets

    @property
    def CouplingLength(self):
        return self.obj.CouplingLength

    @property
    def Color(self):
        return self.obj.Color

    @FallTime.setter
    def FallTime(self, FallTime):
        self.obj.FallTime=FallTime

    @property
    def MaxDriverVoltage(self):
        return self.obj.MaxDriverVoltage

    @property
    def UnroutedSegments(self):
        return self.obj.UnroutedSegments

    @property
    def MetalInShape(self):
        return self.obj.MetalInShape

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @property
    def GetCouplingNetLength(self):
        return self.obj.GetCouplingNetLength

    @Color.setter
    def Color(self, Color):
        self.obj.Color=Color

