# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcLayerStackup(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def SignalThickness(self):
        return self.obj.SignalThickness

    @property
    def InsulatorThickness(self):
        return self.obj.InsulatorThickness

    @SignalThickness.setter
    def SignalThickness(self, SignalThickness):
        self.obj.SignalThickness=SignalThickness

    @property
    def DielectricConstant(self):
        return self.obj.DielectricConstant

    @InsulatorThickness.setter
    def InsulatorThickness(self, InsulatorThickness):
        self.obj.InsulatorThickness=InsulatorThickness

    @property
    def Resistivity(self):
        return self.obj.Resistivity

    @DielectricConstant.setter
    def DielectricConstant(self, DielectricConstant):
        self.obj.DielectricConstant=DielectricConstant

    @property
    def LossTangent(self):
        return self.obj.LossTangent

    @Resistivity.setter
    def Resistivity(self, Resistivity):
        self.obj.Resistivity=Resistivity

    @property
    def Layers(self):
        return self.obj.Layers

    @property
    def MetalLayers(self):
        return self.obj.MetalLayers

    @property
    def Conductivity(self):
        return self.obj.Conductivity

    @LossTangent.setter
    def LossTangent(self, LossTangent):
        self.obj.LossTangent=LossTangent

    @Conductivity.setter
    def Conductivity(self, Conductivity):
        self.obj.Conductivity=Conductivity

