# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcSegment2(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Radius(self):
        return self.obj.Radius

    @property
    def CenterX(self):
        return self.obj.CenterX

    @property
    def CenterY(self):
        return self.obj.CenterY

    @property
    def IsArc(self):
        return self.obj.IsArc

