# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcShareList(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Notes(self):
        return self.obj.Notes

    @property
    def Violations(self):
        return self.obj.Violations

    @property
    def AddViolation(self):
        return self.obj.AddViolation

    @property
    def RemoveViolation(self):
        return self.obj.RemoveViolation

    @property
    def RemoveAll(self):
        return self.obj.RemoveAll

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def SetName(self):
        return self.obj.SetName

    @property
    def Export(self):
        return self.obj.Export

    @Notes.setter
    def Notes(self, Notes):
        self.obj.Notes=Notes

