# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcObject(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ObjectType(self):
        return self.obj.ObjectType

    @property
    def Document(self):
        return self.obj.Document

    @property
    def ObjectTypeStr(self):
        return self.obj.ObjectTypeStr

    @property
    def ToString(self):
        return self.obj.ToString

    @property
    def Geometry(self):
        return self.obj.Geometry

    @property
    def Name(self):
        return self.obj.Name

