# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPin4(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def PackageDelay(self):
        return self.obj.PackageDelay

    @property
    def PackageLength(self):
        return self.obj.PackageLength

    @PackageDelay.setter
    def PackageDelay(self, PackageDelay):
        self.obj.PackageDelay=PackageDelay

    @PackageLength.setter
    def PackageLength(self, PackageLength):
        self.obj.PackageLength=PackageLength

