# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPathFinder(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def MaxLength(self):
        return self.obj.MaxLength

    @property
    def MinWidth(self):
        return self.obj.MinWidth

    @MaxLength.setter
    def MaxLength(self, MaxLength):
        self.obj.MaxLength=MaxLength

    @property
    def MaxRadius(self):
        return self.obj.MaxRadius

    @MinWidth.setter
    def MinWidth(self, MinWidth):
        self.obj.MinWidth=MinWidth

    @property
    def UseElectricalNets(self):
        return self.obj.UseElectricalNets

    @MaxRadius.setter
    def MaxRadius(self, MaxRadius):
        self.obj.MaxRadius=MaxRadius

    @property
    def SegmentsAllowed(self):
        return self.obj.SegmentsAllowed

    @UseElectricalNets.setter
    def UseElectricalNets(self, UseElectricalNets):
        self.obj.UseElectricalNets=UseElectricalNets

    @property
    def AreaFillsAllowed(self):
        return self.obj.AreaFillsAllowed

    @SegmentsAllowed.setter
    def SegmentsAllowed(self, SegmentsAllowed):
        self.obj.SegmentsAllowed=SegmentsAllowed

    @property
    def LayerChangeAllowed(self):
        return self.obj.LayerChangeAllowed

    @AreaFillsAllowed.setter
    def AreaFillsAllowed(self, AreaFillsAllowed):
        self.obj.AreaFillsAllowed=AreaFillsAllowed

    @property
    def IncludePinViaHeights(self):
        return self.obj.IncludePinViaHeights

    @LayerChangeAllowed.setter
    def LayerChangeAllowed(self, LayerChangeAllowed):
        self.obj.LayerChangeAllowed=LayerChangeAllowed

    @property
    def Point2Point(self):
        return self.obj.Point2Point

    @property
    def InShape(self):
        return self.obj.InShape

    @property
    def ToObject(self):
        return self.obj.ToObject

    @IncludePinViaHeights.setter
    def IncludePinViaHeights(self, IncludePinViaHeights):
        self.obj.IncludePinViaHeights=IncludePinViaHeights

