# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcCreepage(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def SimulationStatus(self):
        return self.obj.SimulationStatus

    @property
    def ShortestPath(self):
        return self.obj.ShortestPath

    @property
    def RedZone(self):
        return self.obj.RedZone

    @property
    def OrangeZone(self):
        return self.obj.OrangeZone

    @property
    def YellowZone(self):
        return self.obj.YellowZone

    @property
    def HighGeometry(self):
        return self.obj.HighGeometry

    @property
    def LowGeometry(self):
        return self.obj.LowGeometry

    @property
    def Shortcut(self):
        return self.obj.Shortcut

    @property
    def ShortestDistance(self):
        return self.obj.ShortestDistance

