# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPropertyCondition(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Relation(self):
        return self.obj.Relation

    @property
    def Property(self):
        return self.obj.Property

    @Relation.setter
    def Relation(self, Relation):
        self.obj.Relation=Relation

    @property
    def Value(self):
        return self.obj.Value

    @Property.setter
    def Property(self, Property):
        self.obj.Property=Property

    @property
    def Validation(self):
        return self.obj.Validation

    @property
    def Delete(self):
        return self.obj.Delete

    @Value.setter
    def Value(self, Value):
        self.obj.Value=Value

