# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcFormat(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def AngleUnit(self):
        return self.obj.AngleUnit

    @property
    def DistanceUnit(self):
        return self.obj.DistanceUnit

    @AngleUnit.setter
    def AngleUnit(self, AngleUnit):
        self.obj.AngleUnit=AngleUnit

    @property
    def VoltageUnit(self):
        return self.obj.VoltageUnit

    @DistanceUnit.setter
    def DistanceUnit(self, DistanceUnit):
        self.obj.DistanceUnit=DistanceUnit

    @property
    def CapacitanceUnit(self):
        return self.obj.CapacitanceUnit

    @VoltageUnit.setter
    def VoltageUnit(self, VoltageUnit):
        self.obj.VoltageUnit=VoltageUnit

    @property
    def ResistanceUnit(self):
        return self.obj.ResistanceUnit

    @CapacitanceUnit.setter
    def CapacitanceUnit(self, CapacitanceUnit):
        self.obj.CapacitanceUnit=CapacitanceUnit

    @property
    def InductanceUnit(self):
        return self.obj.InductanceUnit

    @ResistanceUnit.setter
    def ResistanceUnit(self, ResistanceUnit):
        self.obj.ResistanceUnit=ResistanceUnit

    @property
    def FrequencyUnit(self):
        return self.obj.FrequencyUnit

    @InductanceUnit.setter
    def InductanceUnit(self, InductanceUnit):
        self.obj.InductanceUnit=InductanceUnit

    @property
    def TimeUnit(self):
        return self.obj.TimeUnit

    @FrequencyUnit.setter
    def FrequencyUnit(self, FrequencyUnit):
        self.obj.FrequencyUnit=FrequencyUnit

    @property
    def CurrentUnit(self):
        return self.obj.CurrentUnit

    @TimeUnit.setter
    def TimeUnit(self, TimeUnit):
        self.obj.TimeUnit=TimeUnit

    @CurrentUnit.setter
    def CurrentUnit(self, CurrentUnit):
        self.obj.CurrentUnit=CurrentUnit

