# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcModelIndex(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Save(self):
        return self.obj.Save

    @property
    def AddModelFile(self):
        return self.obj.AddModelFile

    @property
    def SetModelPath(self):
        return self.obj.SetModelPath

    @property
    def GetModelPath(self):
        return self.obj.GetModelPath

    @property
    def Load(self):
        return self.obj.Load

