# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcNetPairCondition(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Relation(self):
        return self.obj.Relation

    @property
    def PositiveNameValue(self):
        return self.obj.PositiveNameValue

    @Relation.setter
    def Relation(self, Relation):
        self.obj.Relation=Relation

    @property
    def NegativeNameValue(self):
        return self.obj.NegativeNameValue

    @PositiveNameValue.setter
    def PositiveNameValue(self, PositiveNameValue):
        self.obj.PositiveNameValue=PositiveNameValue

    @property
    def Validation(self):
        return self.obj.Validation

    @property
    def Delete(self):
        return self.obj.Delete

    @NegativeNameValue.setter
    def NegativeNameValue(self, NegativeNameValue):
        self.obj.NegativeNameValue=NegativeNameValue

