# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcPhysicalNet(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def NetClass(self):
        return self.obj.NetClass

    @property
    def Pins(self):
        return self.obj.Pins

    @property
    def Vias(self):
        return self.obj.Vias

    @property
    def Traces(self):
        return self.obj.Traces

    @property
    def AreaFills(self):
        return self.obj.AreaFills

    @property
    def Violations(self):
        return self.obj.Violations

    @property
    def CouplingAssignments(self):
        return self.obj.CouplingAssignments

    @property
    def CouplingElements(self):
        return self.obj.CouplingElements

    @property
    def ElecNet(self):
        return self.obj.ElecNet

    @property
    def Length(self):
        return self.obj.Length

    @property
    def Color(self):
        return self.obj.Color

    @property
    def DiffPairNet(self):
        return self.obj.DiffPairNet

    @property
    def Unconnected(self):
        return self.obj.Unconnected

    @property
    def UnroutedSegments(self):
        return self.obj.UnroutedSegments

    @property
    def MetalInShape(self):
        return self.obj.MetalInShape

    @property
    def ObjectsInShape(self):
        return self.obj.ObjectsInShape

    @property
    def ObjectsInVicinity(self):
        return self.obj.ObjectsInVicinity

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @Color.setter
    def Color(self, Color):
        self.obj.Color=Color

