# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcTrace(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def Width(self):
        return self.obj.Width

    @property
    def TransLines(self):
        return self.obj.TransLines

    @property
    def Segments(self):
        return self.obj.Segments

    @property
    def Length(self):
        return self.obj.Length

    @property
    def StartX(self):
        return self.obj.StartX

    @property
    def StartY(self):
        return self.obj.StartY

    @property
    def EndX(self):
        return self.obj.EndX

    @property
    def EndY(self):
        return self.obj.EndY

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @property
    def Net(self):
        return self.obj.Net

