# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcComponent4(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def AssignModelBy(self):
        return self.obj.AssignModelBy

    @property
    def ModelByType(self):
        return self.obj.ModelByType

    @property
    def ModelBy(self):
        return self.obj.ModelBy

    @property
    def SetType(self):
        return self.obj.SetType

