# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcEnclosureSlotGroup(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def NumberOfSlots(self):
        return self.obj.NumberOfSlots

    @property
    def SlotLength(self):
        return self.obj.SlotLength

    @NumberOfSlots.setter
    def NumberOfSlots(self, NumberOfSlots):
        self.obj.NumberOfSlots=NumberOfSlots

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def SetName(self):
        return self.obj.SetName

    @SlotLength.setter
    def SlotLength(self, SlotLength):
        self.obj.SlotLength=SlotLength

