# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcRule4(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def NewChildGroup(self):
        return self.obj.NewChildGroup

    @property
    def ConstraintClasses(self):
        return self.obj.ConstraintClasses

