# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcBoard2(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Cavities(self):
        return self.obj.Cavities

    @property
    def LayoutFilePath(self):
        return self.obj.LayoutFilePath

    @property
    def ConstraintsFilePath(self):
        return self.obj.ConstraintsFilePath

    @property
    def BoardRegions(self):
        return self.obj.BoardRegions

