# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcGraph(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def NewEdge(self):
        return self.obj.NewEdge

    @property
    def RemoveNode(self):
        return self.obj.RemoveNode

    @property
    def RemoveEdge(self):
        return self.obj.RemoveEdge

    @property
    def GetEdges(self):
        return self.obj.GetEdges

    @property
    def SetName(self):
        return self.obj.SetName

    @property
    def GetNodesByObjects(self):
        return self.obj.GetNodesByObjects

    @property
    def Nodes(self):
        return self.obj.Nodes

    @property
    def Edges(self):
        return self.obj.Edges

    @property
    def Weight(self):
        return self.obj.Weight

    @property
    def IsAcyclic(self):
        return self.obj.IsAcyclic

    @property
    def IsDirected(self):
        return self.obj.IsDirected

    @property
    def Store(self):
        return self.obj.Store

    @property
    def WeightUnit(self):
        return self.obj.WeightUnit

    @property
    def NewNode(self):
        return self.obj.NewNode

    @WeightUnit.setter
    def WeightUnit(self, WeightUnit):
        self.obj.WeightUnit=WeightUnit

