# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcViolation(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ViolationType(self):
        return self.obj.ViolationType

    @property
    def Rank(self):
        return self.obj.Rank

    @property
    def Id(self):
        return self.obj.Id

    @property
    def IsPositioned(self):
        return self.obj.IsPositioned

    @Rank.setter
    def Rank(self, Rank):
        self.obj.Rank=Rank

    @property
    def PosX(self):
        return self.obj.PosX

    @IsPositioned.setter
    def IsPositioned(self, IsPositioned):
        self.obj.IsPositioned=IsPositioned

    @property
    def PosY(self):
        return self.obj.PosY

    @PosX.setter
    def PosX(self, PosX):
        self.obj.PosX=PosX

    @property
    def ParentScript(self):
        return self.obj.ParentScript

    @property
    def Status(self):
        return self.obj.Status

    @PosY.setter
    def PosY(self, PosY):
        self.obj.PosY=PosY

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def Description(self):
        return self.obj.Description

    @Status.setter
    def Status(self, Status):
        self.obj.Status=Status

    @property
    def ParentRule(self):
        return self.obj.ParentRule

    @property
    def ViolationGroups(self):
        return self.obj.ViolationGroups

    @property
    def Severity(self):
        return self.obj.Severity

    @property
    def DefineParameter(self):
        return self.obj.DefineParameter

    @property
    def DefineCommand(self):
        return self.obj.DefineCommand

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def Commit(self):
        return self.obj.Commit

    @Description.setter
    def Description(self, Description):
        self.obj.Description=Description

