# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcTextReport(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Title(self):
        return self.obj.Title

    @property
    def Note(self):
        return self.obj.Note

    @Title.setter
    def Title(self, Title):
        self.obj.Title=Title

    @property
    def Open(self):
        return self.obj.Open

    @property
    def ReportViolationType(self):
        return self.obj.ReportViolationType

    @property
    def Close(self):
        return self.obj.Close

    @property
    def CreateColumns(self):
        return self.obj.CreateColumns

    @property
    def SetColumnCaption(self):
        return self.obj.SetColumnCaption

    @property
    def SetColumnWidth(self):
        return self.obj.SetColumnWidth

    @property
    def SetIgnoreColumn(self):
        return self.obj.SetIgnoreColumn

    @property
    def SetColumnRightAlign(self):
        return self.obj.SetColumnRightAlign

    @property
    def SetSortBy(self):
        return self.obj.SetSortBy

    @Note.setter
    def Note(self, Note):
        self.obj.Note=Note

