# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcConditionGroup(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Relation(self):
        return self.obj.Relation

    @property
    def Conditions(self):
        return self.obj.Conditions

    @property
    def NewConditionGroup(self):
        return self.obj.NewConditionGroup

    @property
    def NewPropertyCondition(self):
        return self.obj.NewPropertyCondition

    @property
    def NewNetPairCondition(self):
        return self.obj.NewNetPairCondition

    @property
    def NewAttributeCondition(self):
        return self.obj.NewAttributeCondition

    @property
    def Delete(self):
        return self.obj.Delete

    @property
    def Reset(self):
        return self.obj.Reset

    @property
    def Validation(self):
        return self.obj.Validation

    @Relation.setter
    def Relation(self, Relation):
        self.obj.Relation=Relation

