# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcSetupWizard(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Prev(self):
        return self.obj.Prev

    @property
    def Exit(self):
        return self.obj.Exit

    @property
    def Finish(self):
        return self.obj.Finish

    @property
    def HTML(self):
        return self.obj.HTML

    @property
    def Select(self):
        return self.obj.Select

    @property
    def ApplicationType(self):
        return self.obj.ApplicationType

    @property
    def Next(self):
        return self.obj.Next

