# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcFiducial(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Pads(self):
        return self.obj.Pads

    @property
    def PositionX(self):
        return self.obj.PositionX

    @property
    def PositionY(self):
        return self.obj.PositionY

    @property
    def Side(self):
        return self.obj.Side

    @property
    def Orientation(self):
        return self.obj.Orientation

