# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcDbObject(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Selected(self):
        return self.obj.Selected

    @property
    def Highlighted(self):
        return self.obj.Highlighted

    @Selected.setter
    def Selected(self, Selected):
        self.obj.Selected=Selected

    @Highlighted.setter
    def Highlighted(self, Highlighted):
        self.obj.Highlighted=Highlighted

