# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcView3(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Enabled(self):
        return self.obj.Enabled

    @Enabled.setter
    def Enabled(self, Enabled):
        self.obj.Enabled=Enabled

