# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcGraphNode(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Edges(self):
        return self.obj.Edges

    @property
    def Store(self):
        return self.obj.Store

    @property
    def SetName(self):
        return self.obj.SetName

