# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcAreaFill(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def Net(self):
        return self.obj.Net

    @property
    def OutlineArea(self):
        return self.obj.OutlineArea

    @property
    def CopperArea(self):
        return self.obj.CopperArea

    @property
    def ConnectedPins(self):
        return self.obj.ConnectedPins

    @property
    def ConnectedVias(self):
        return self.obj.ConnectedVias

    @property
    def ConnectedTraces(self):
        return self.obj.ConnectedTraces

    @property
    def Attributes(self):
        return self.obj.Attributes

    @property
    def AddAttribute(self):
        return self.obj.AddAttribute

    @property
    def Violations(self):
        return self.obj.Violations

