# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcCollection(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Count(self):
        return self.obj.Count

    @property
    def _NewEnum(self):
        return self.obj._NewEnum

    @property
    def Add(self):
        return self.obj.Add

    @property
    def Remove(self):
        return self.obj.Remove

    @property
    def Merge(self):
        return self.obj.Merge

    @property
    def Reset(self):
        return self.obj.Reset

    @property
    def Sort(self):
        return self.obj.Sort

    @property
    def SetName(self):
        return self.obj.SetName

    @property
    def Item(self):
        return self.obj.Item

