# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-12:11:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHyperLynxDrcSeriesPairData(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def PinPlus(self):
        return self.obj.PinPlus

    @property
    def PinMinus(self):
        return self.obj.PinMinus

    @PinPlus.setter
    def PinPlus(self, PinPlus):
        self.obj.PinPlus=PinPlus

    @property
    def Model(self):
        return self.obj.Model

    @PinMinus.setter
    def PinMinus(self, PinMinus):
        self.obj.PinMinus=PinMinus

    @property
    def Delete(self):
        return self.obj.Delete

    @Model.setter
    def Model(self, Model):
        self.obj.Model=Model

