# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLBoard(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Suffix(self):
        return self.obj.Suffix

    @property
    def Stackup(self):
        return self.obj.Stackup

    @property
    def Stackups(self):
        return self.obj.Stackups

    @property
    def Nets(self):
        return self.obj.Nets

    @property
    def Components(self):
        return self.obj.Components

    @property
    def FindNet(self):
        return self.obj.FindNet

    @property
    def FindComponent(self):
        return self.obj.FindComponent

    @property
    def FindStackup(self):
        return self.obj.FindStackup

    @property
    def CreateStackup(self):
        return self.obj.CreateStackup

    @property
    def DeleteStackup(self):
        return self.obj.DeleteStackup

    @property
    def FileName(self):
        return self.obj.FileName

