# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLDbPin(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def FullName(self):
        return self.obj.FullName

    @property
    def Component(self):
        return self.obj.Component

    @property
    def Net(self):
        return self.obj.Net

    @property
    def Model(self):
        return self.obj.Model

    @property
    def AssignModel(self):
        return self.obj.AssignModel

    @property
    def Name(self):
        return self.obj.Name

