# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLDesign(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Boards(self):
        return self.obj.Boards

    @property
    def Stackups(self):
        return self.obj.Stackups

    @property
    def Stackup(self):
        return self.obj.Stackup

    @property
    def Nets(self):
        return self.obj.Nets

    @property
    def Components(self):
        return self.obj.Components

    @property
    def Padstacks(self):
        return self.obj.Padstacks

    @property
    def TriDAreas(self):
        return self.obj.TriDAreas

    @property
    def SimSettings(self):
        return self.obj.SimSettings

    @property
    def CrosstalkSettings(self):
        return self.obj.CrosstalkSettings

    @property
    def FindNet(self):
        return self.obj.FindNet

    @property
    def CurSelNet(self):
        return self.obj.CurSelNet

    @property
    def Viewer(self):
        return self.obj.Viewer

    @property
    def SelectNet(self):
        return self.obj.SelectNet

    @property
    def SelectedNets(self):
        return self.obj.SelectedNets

    @property
    def SelectNets(self):
        return self.obj.SelectNets

    @property
    def FindComponent(self):
        return self.obj.FindComponent

    @property
    def FindPadstack(self):
        return self.obj.FindPadstack

    @property
    def FindStackup(self):
        return self.obj.FindStackup

    @property
    def CreateStackup(self):
        return self.obj.CreateStackup

    @property
    def DeleteStackup(self):
        return self.obj.DeleteStackup

    @property
    def Save(self):
        return self.obj.Save

    @property
    def Search3DAreas(self):
        return self.obj.Search3DAreas

    @property
    def Delete3DArea(self):
        return self.obj.Delete3DArea

    @CurSelNet.setter
    def CurSelNet(self, CurSelNet):
        self.obj.CurSelNet=CurSelNet

