# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLDbSegment(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def X1(self):
        return self.obj.X1

    @property
    def Y1(self):
        return self.obj.Y1

    @property
    def X2(self):
        return self.obj.X2

    @property
    def Y2(self):
        return self.obj.Y2

    @property
    def Width(self):
        return self.obj.Width

    @property
    def Stackup(self):
        return self.obj.Stackup

    @property
    def Layer(self):
        return self.obj.Layer

