# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLPadstack(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ActualDrillSize(self):
        return self.obj.ActualDrillSize

    @property
    def Name(self):
        return self.obj.Name

    @property
    def FinishDrillHole(self):
        return self.obj.FinishDrillHole

    @ActualDrillSize.setter
    def ActualDrillSize(self, ActualDrillSize):
        self.obj.ActualDrillSize=ActualDrillSize

    @property
    def StartLayer(self):
        return self.obj.StartLayer

    @FinishDrillHole.setter
    def FinishDrillHole(self, FinishDrillHole):
        self.obj.FinishDrillHole=FinishDrillHole

    @property
    def EndLayer(self):
        return self.obj.EndLayer

    @StartLayer.setter
    def StartLayer(self, StartLayer):
        self.obj.StartLayer=StartLayer

    @property
    def Pads(self):
        return self.obj.Pads

    @EndLayer.setter
    def EndLayer(self, EndLayer):
        self.obj.EndLayer=EndLayer

