# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLPad(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Type(self):
        return self.obj.Type

    @property
    def Shape(self):
        return self.obj.Shape

    @property
    def Layer(self):
        return self.obj.Layer

    @property
    def Size(self):
        return self.obj.Size

    @Shape.setter
    def Shape(self, Shape):
        self.obj.Shape=Shape

    @property
    def Height(self):
        return self.obj.Height

    @Size.setter
    def Size(self, Size):
        self.obj.Size=Size

    @property
    def Angle(self):
        return self.obj.Angle

    @Height.setter
    def Height(self, Height):
        self.obj.Height=Height

    @property
    def OffsetX(self):
        return self.obj.OffsetX

    @Angle.setter
    def Angle(self, Angle):
        self.obj.Angle=Angle

    @property
    def OffsetY(self):
        return self.obj.OffsetY

    @OffsetX.setter
    def OffsetX(self, OffsetX):
        self.obj.OffsetX=OffsetX

    @OffsetY.setter
    def OffsetY(self, OffsetY):
        self.obj.OffsetY=OffsetY

