# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLRect(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Bottom(self):
        return self.obj.Bottom

    @property
    def Right(self):
        return self.obj.Right

    @property
    def Top(self):
        return self.obj.Top

    @property
    def Left(self):
        return self.obj.Left

