# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLScmSupplyNet(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def InUse(self):
        return self.obj.InUse

    @property
    def Voltage(self):
        return self.obj.Voltage

    @property
    def Name(self):
        return self.obj.Name

    @Voltage.setter
    def Voltage(self, Voltage):
        self.obj.Voltage=Voltage

