# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLScmDiffIc(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Pin1Name(self):
        return self.obj.Pin1Name

    @property
    def Pin2Name(self):
        return self.obj.Pin2Name

    @property
    def Model1(self):
        return self.obj.Model1

    @property
    def Model2(self):
        return self.obj.Model2

    @property
    def AssignModel(self):
        return self.obj.AssignModel

    @property
    def Rename(self):
        return self.obj.Rename

    @property
    def RefDes(self):
        return self.obj.RefDes

