# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLSimSettings(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def Crosstalk(self):
        return self.obj.Crosstalk

    @property
    def Lossy(self):
        return self.obj.Lossy

    @Crosstalk.setter
    def Crosstalk(self, Crosstalk):
        self.obj.Crosstalk=Crosstalk

    @property
    def TrapezoidTraces(self):
        return self.obj.TrapezoidTraces

    @Lossy.setter
    def Lossy(self, Lossy):
        self.obj.Lossy=Lossy

    @property
    def SurfaceRoughness(self):
        return self.obj.SurfaceRoughness

    @TrapezoidTraces.setter
    def TrapezoidTraces(self, TrapezoidTraces):
        self.obj.TrapezoidTraces=TrapezoidTraces

    @property
    def NonfunctionPads(self):
        return self.obj.NonfunctionPads

    @SurfaceRoughness.setter
    def SurfaceRoughness(self, SurfaceRoughness):
        self.obj.SurfaceRoughness=SurfaceRoughness

    @NonfunctionPads.setter
    def NonfunctionPads(self, NonfunctionPads):
        self.obj.NonfunctionPads=NonfunctionPads

