# coding=utf-8
"""
This file is autogenerated by python script @ 20200808-20:13:09
"""
import sys
import os
import datetime,time

#from PowerPCBEnums import *

__author__ = 'SayCV'

import logging

logger = logging.getLogger(__name__)

class IHLViewer(object):
    def __init__(self, obj=None):
        self.obj = obj


    @property
    def ZoomExtents(self):
        return self.obj.ZoomExtents

    @property
    def WindowWidth(self):
        return self.obj.WindowWidth

    @property
    def WindowHeight(self):
        return self.obj.WindowHeight

    @property
    def GetDesignExtents(self):
        return self.obj.GetDesignExtents

    @property
    def GetZoomExtents(self):
        return self.obj.GetZoomExtents

    @property
    def GetWindowSize(self):
        return self.obj.GetWindowSize

    @property
    def ZoomTo(self):
        return self.obj.ZoomTo

    @property
    def FitToWindow(self):
        return self.obj.FitToWindow

    @property
    def DesignToWindowX(self):
        return self.obj.DesignToWindowX

    @property
    def DesignToWindowY(self):
        return self.obj.DesignToWindowY

    @property
    def WindowToDesignX(self):
        return self.obj.WindowToDesignX

    @property
    def WindowToDesignY(self):
        return self.obj.WindowToDesignY

    @property
    def ScaleToWindow(self):
        return self.obj.ScaleToWindow

    @property
    def ScaleToDesign(self):
        return self.obj.ScaleToDesign

    @property
    def DesignExtents(self):
        return self.obj.DesignExtents

